package xenosoft.imldintelligence.common.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "audit_log", autoResultMap = true)
public class AuditLog {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long userId;
    private String userRole;
    private String action;
    private String resourceType;
    private String resourceId;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode beforeData;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode afterData;
    private String ipAddress;
    private String deviceInfo;
    private String appVersion;
    private String traceId;
    private java.time.OffsetDateTime createdAt;

    
}
/**
 * CREATE TABLE audit_log (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                           user_id                 BIGINT REFERENCES user_account(id),
                           user_role               VARCHAR(64),
                           action                  VARCHAR(32) NOT NULL,             -- CREATE/READ/UPDATE/DELETE/SIGN/EXPORT
                           resource_type           VARCHAR(64) NOT NULL,             -- PATIENT/REPORT/GENETIC_DATA/QUESTIONNAIRE
                           resource_id             VARCHAR(128),
                           before_data             JSONB,
                           after_data              JSONB,
                           ip_address              VARCHAR(64),
                           device_info             VARCHAR(255),
                           app_version             VARCHAR(64),
                           trace_id                VARCHAR(64),
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
