package xenosoft.imldintelligence.common.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@lombok.Data
@TableName("model_invocation_log")
public class ModelInvocationLog {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long sessionId;
    private Long modelRegistryId;
    private String provider;
    private String requestId;
    private String inputDigest;
    private String outputDigest;
    private Integer latencyMs;
    private Integer tokenIn;
    private Integer tokenOut;
    private java.math.BigDecimal costAmount;
    private String status;
    private String errorMessage;
    private java.time.OffsetDateTime createdAt;
    
}
/**
 * CREATE TABLE model_invocation_log (
                                      id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                      session_id              BIGINT REFERENCES diagnosis_session(id),
                                      model_registry_id       BIGINT REFERENCES model_registry(id),
                                      provider                VARCHAR(64),
                                      request_id              VARCHAR(128),
                                      input_digest            VARCHAR(128),                     -- 输入摘要（避免存明文）
                                      output_digest           VARCHAR(128),                     -- 输出摘要
                                      latency_ms              INT,
                                      token_in                INT,
                                      token_out               INT,
                                      cost_amount             NUMERIC(12,4),
                                      status                  VARCHAR(32) NOT NULL,             -- SUCCESS/FAILED/TIMEOUT
                                      error_message           TEXT,
                                      created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */