package xenosoft.imldintelligence.common.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@lombok.Data
@TableName("sensitive_data_access_log")
public class SensitiveDataAccessLog {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long userId;
    private String sensitiveType;
    private String resourceType;
    private String resourceId;
    private String accessReason;
    private String accessResult;
    private String ipAddress;
    private java.time.OffsetDateTime createdAt;
}
/**
 * CREATE TABLE sensitive_data_access_log (
                                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                           user_id                 BIGINT REFERENCES user_account(id),
                                           sensitive_type          VARCHAR(32) NOT NULL,             -- GENETIC/ID_CARD/MEDICAL_RECORD
                                           resource_type           VARCHAR(64) NOT NULL,
                                           resource_id             VARCHAR(128),
                                           access_reason           VARCHAR(255),
                                           access_result           VARCHAR(32) NOT NULL,             -- ALLOW/DENY
                                           ip_address              VARCHAR(64),
                                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */