package xenosoft.imldintelligence.module.careplan.model;

@lombok.Data
public class CarePlan {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private String diseaseCode;
    private String planType;
    private String enrollmentType;
    private Long templateId;
    private String status;
    private java.time.LocalDate startDate;
    private java.time.LocalDate endDate;
    private Long createdBy;
    private java.time.OffsetDateTime createdAt;
    
}
/**
 * CREATE TABLE care_plan (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                           patient_id              BIGINT NOT NULL REFERENCES patient(id),
                           disease_code            VARCHAR(64) NOT NULL,
                           plan_type               VARCHAR(32) NOT NULL,             -- STANDARD/VIP
                           enrollment_type         VARCHAR(32) NOT NULL,             -- DOCTOR_ASSIGNED/AUTO/PATIENT_PURCHASED
                           template_id             BIGINT REFERENCES care_plan_template(id),
                           status                  VARCHAR(32) NOT NULL,             -- ACTIVE/PAUSED/COMPLETED/TERMINATED
                           start_date              DATE NOT NULL,
                           end_date                DATE,
                           created_by              BIGINT REFERENCES user_account(id),
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
