package xenosoft.imldintelligence.module.careplan.model;

import com.fasterxml.jackson.databind.JsonNode;
@lombok.Data
public class PatientReportedData {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long carePlanId;
    private String indicatorCode;
    private Double valueNumeric;
    private String valueText;
    private String source;
    private JsonNode deviceInfo;
    private java.time.OffsetDateTime recordedAt;
    private java.time.OffsetDateTime createdAt;
}
/**
 * CREATE TABLE patient_reported_data (
                                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                       patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                       care_plan_id            BIGINT REFERENCES care_plan(id),
                                       indicator_code          VARCHAR(64) NOT NULL,             -- 可复用 indicator_dict.code
                                       value_numeric           NUMERIC(18,6),
                                       value_text              VARCHAR(200),
                                       source                  VARCHAR(32) NOT NULL,             -- MANUAL/DEVICE_SYNC
                                       device_info             JSONB,
                                       recorded_at             TIMESTAMPTZ NOT NULL,
                                       created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
