spring:
  application:
    name: imld-intelligence
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/imld_core?sslmode=disable&characterEncoding=utf8
    username: postgres
    password: L0-postgres

mybatis:
  mapper-locations: classpath:xenosoft/imldintelligence/modules/**/internal/repository/*.xml
  configuration:
    map-underscore-to-camel-case: true
