package xenosoft.imldintelligence.module.payment.internal.model;

@lombok.Data
public class VipOrder {
    private Long id;
    private Long tenantId;
    private String orderNo;
    private Long tocUserId;
    private Long planId;
    private String orderStatus;
    private java.math.BigDecimal amount;
    private java.time.OffsetDateTime paidAt;
    private String channel;
    private java.time.OffsetDateTime createdAt;
}

/**
 * CREATE TABLE vip_order (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                           order_no                VARCHAR(64) NOT NULL,
                           toc_user_id             BIGINT NOT NULL REFERENCES toc_user(id),
                           plan_id                 BIGINT NOT NULL REFERENCES vip_plan(id),
                           order_status            VARCHAR(32) NOT NULL,             -- CREATED/PAID/CANCELLED/REFUNDED
                           amount                  NUMERIC(12,2) NOT NULL,
                           paid_at                 TIMESTAMPTZ,
                           channel                 VARCHAR(32),                      -- WECHAT/ALIPAY/OTHER
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                           UNIQUE (tenant_id, order_no)
);
 */