package xenosoft.imldintelligence.module.payment.internal.model;

@lombok.Data
public class VipPlan {
    private Long id;
    private Long tenantId;
    private String planCode;
    private String planName;
    private Integer durationDays;
    private java.math.BigDecimal priceAmount;
    private String currencyCode;
    private String status;
    private java.time.OffsetDateTime createdAt;
}

/**
 * CREATE TABLE vip_plan (
                          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                          plan_code               VARCHAR(64) NOT NULL,
                          plan_name               VARCHAR(100) NOT NULL,
                          duration_days           INT NOT NULL,
                          price_amount            NUMERIC(12,2) NOT NULL,
                          currency_code           VARCHAR(16) NOT NULL DEFAULT 'CNY',
                          status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                          created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                          UNIQUE (tenant_id, plan_code)
);
 */