package xenosoft.imldintelligence.module.payment.internal.model;

@lombok.Data
public class VipSubscription {
    private Long id;
    private Long tenantId;
    private Long tocUserId;
    private Long planId;
    private Long orderId;
    private String subscriptionStatus;
    private java.time.OffsetDateTime startAt;
    private java.time.OffsetDateTime endAt;
    private java.time.OffsetDateTime createdAt;
}

/**
 * 
CREATE TABLE vip_subscription (
                                  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                  toc_user_id             BIGINT NOT NULL REFERENCES toc_user(id),
                                  plan_id                 BIGINT NOT NULL REFERENCES vip_plan(id),
                                  order_id                BIGINT NOT NULL REFERENCES vip_order(id),
                                  subscription_status     VARCHAR(32) NOT NULL,             -- ACTIVE/EXPIRED/CANCELLED
                                  start_at                TIMESTAMPTZ NOT NULL,
                                  end_at                  TIMESTAMPTZ NOT NULL,
                                  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

 */
