package xenosoft.imldintelligence.module.diagnoses.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "diagnosis_result", autoResultMap = true)
public class DiagnosisResult{
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long sessionId;
    private String diseaseCode;
    private String diseaseName;
    private Double confidence;
    private Integer rankNo;
    private String riskLevel;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode evidenceJson;
    private Boolean isDisplayToPatient;
    private java.time.OffsetDateTime createdAt;
}

/**
 * Schema:
 * CREATE TABLE diagnosis_result (
                                  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                  session_id              BIGINT NOT NULL REFERENCES diagnosis_session(id),
                                  disease_code            VARCHAR(64) NOT NULL,
                                  disease_name            VARCHAR(200) NOT NULL,
                                  confidence              NUMERIC(8,6),
                                  rank_no                 INT NOT NULL,
                                  risk_level              VARCHAR(32),                      -- LOW/MEDIUM/HIGH
                                  evidence_json           JSONB,
                                  is_display_to_patient   BOOLEAN NOT NULL DEFAULT FALSE,   -- 中间结果默认不对患者展示
                                  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
