package xenosoft.imldintelligence.module.diagnoses.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@lombok.Data
@TableName("diagnosis_recommendation")
public class DiagnosisRecommendation {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long sessionId;
    private String recType;
    private String content;
    private Integer priority;
    private String reason;
    private java.time.OffsetDateTime createdAt;
}

/**
 * Schema:
 * CREATE TABLE diagnosis_recommendation (
                                          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                          session_id              BIGINT NOT NULL REFERENCES diagnosis_session(id),
                                          rec_type                VARCHAR(32) NOT NULL,             -- EXAM/LAB/GENETIC/FOLLOWUP/REFERRAL
                                          content                 TEXT NOT NULL,
                                          priority                INT NOT NULL DEFAULT 100,
                                          reason                  TEXT,
                                          created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
