package xenosoft.imldintelligence.module.diagnoses.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "diagnosis_session", autoResultMap = true)
public class DiagnosisSession {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long encounterId;
    private Long doctorId;
    private String triggeredBy;
    private Long modelRegistryId;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode inputSnapshot;
    private String status;
    private java.time.OffsetDateTime startedAt;
    private java.time.OffsetDateTime completedAt;
    private java.time.OffsetDateTime createdAt;

}

/**
 * Schema:
 * CREATE TABLE diagnosis_session (
                                   id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                   patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                   encounter_id            BIGINT REFERENCES encounter(id),
                                   doctor_id               BIGINT REFERENCES user_account(id),
                                   triggered_by            VARCHAR(32) NOT NULL,             -- MANUAL/AUTO
                                   model_registry_id       BIGINT REFERENCES model_registry(id),
                                   input_snapshot          JSONB NOT NULL,                   -- 输入快照
                                   status                  VARCHAR(32) NOT NULL,             -- RUNNING/COMPLETED/FAILED
                                   started_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                   completed_at            TIMESTAMPTZ,
                                   created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
