package xenosoft.imldintelligence.module.diagnoses.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@lombok.Data
@TableName("model_registry")
public class ModelRegistry {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private String modelCode;
    private String modelName;
    private String modelType;
    private String modelVersion;
    private String provider;
    private String status;
    private java.time.OffsetDateTime releasedAt;
    private java.time.OffsetDateTime createdAt;
}

/**
 * CREATE TABLE model_registry (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                model_code              VARCHAR(64) NOT NULL,
                                model_name              VARCHAR(100) NOT NULL,
                                model_type              VARCHAR(32) NOT NULL,             -- RULE/ML/NLP/LLM
                                model_version           VARCHAR(64) NOT NULL,
                                provider                VARCHAR(64),                      -- LOCAL/OPENAI/THIRD_PARTY
                                status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                released_at             TIMESTAMPTZ,
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                UNIQUE (tenant_id, model_code, model_version)
);
 */
