package xenosoft.imldintelligence.module.diagnoses.model;

import com.fasterxml.jackson.databind.JsonNode;

@lombok.Data
public class DiagnosisSession {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long encounterId;
    private Long doctorId;
    private String triggeredBy;
    private Long modelRegistryId;
    private JsonNode inputSnapshotJson;
    private String status;
    private java.time.OffsetDateTime startedAt;
    private java.time.OffsetDateTime completedAt;
    
}

/**
 * Schema:
 * CREATE TABLE diagnosis_session (
                                   id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                   patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                   encounter_id            BIGINT REFERENCES encounter(id),
                                   doctor_id               BIGINT REFERENCES user_account(id),
                                   triggered_by            VARCHAR(32) NOT NULL,             -- MANUAL/AUTO
                                   model_registry_id       BIGINT REFERENCES model_registry(id),
                                   input_snapshot          JSONB NOT NULL,                   -- 输入快照
                                   status                  VARCHAR(32) NOT NULL,             -- RUNNING/COMPLETED/FAILED
                                   started_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                   completed_at            TIMESTAMPTZ,
                                   created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */