package xenosoft.imldintelligence.module.diagnoses.model;

import com.fasterxml.jackson.databind.JsonNode;

@lombok.Data
public class DoctorFeedback {
    private Long id;
    private Long tenantId;
    private Long sessionId;
    private Long resultId;
    private Long doctorId;
    private String action;
    private JsonNode modifiedValue;
    private String rejectReason;
    private java.time.OffsetDateTime createdAt;
}

/**
 * Schema:
 * CREATE TABLE doctor_feedback (
                                 id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                 session_id              BIGINT NOT NULL REFERENCES diagnosis_session(id),
                                 result_id               BIGINT REFERENCES diagnosis_result(id),
                                 doctor_id               BIGINT NOT NULL REFERENCES user_account(id),
                                 action                  VARCHAR(32) NOT NULL,             -- ACCEPT/MODIFY/REJECT/IGNORE
                                 modified_value          JSONB,
                                 reject_reason           VARCHAR(255),
                                 created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
