package xenosoft.imldintelligence.module.notify.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "notification_delivery", autoResultMap = true)
public class NotificationDelivery {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long messageId;
    private String providerName;
    private String providerMessageId;
    private String deliveryStatus;
    private String failReason;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private com.fasterxml.jackson.databind.JsonNode callbackPayload;
    private java.time.OffsetDateTime deliveredAt;
    private java.time.OffsetDateTime createdAt;
}
/**
 * CREATE TABLE notification_delivery (
                                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                       message_id              BIGINT NOT NULL REFERENCES notification_message(id),
                                       provider_name           VARCHAR(64),
                                       provider_message_id     VARCHAR(128),
                                       delivery_status         VARCHAR(32) NOT NULL,             -- ACCEPTED/DELIVERED/FAILED
                                       fail_reason             VARCHAR(255),
                                       callback_payload        JSONB,
                                       delivered_at            TIMESTAMPTZ,
                                       created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
