package xenosoft.imldintelligence.module.notify.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@lombok.Data
@TableName("notification_message")
public class NotificationMessage {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private String bizType;
    private String bizId;
    private String receiverType;
    private Long receiverRefId;
    private String title;
    private String content;
    private String channel;
    private String status;
    private java.time.OffsetDateTime scheduledAt;
    private java.time.OffsetDateTime sentAt;
    private java.time.OffsetDateTime createdAt;
    
}

/**
 * CREATE TABLE notification_message (
                                      id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                      biz_type                VARCHAR(32) NOT NULL,             -- FOLLOWUP/ALERT/REPORT_READY
                                      biz_id                  VARCHAR(64),
                                      receiver_type           VARCHAR(32) NOT NULL,             -- PATIENT/TOC_USER/GUARDIAN/DOCTOR
                                      receiver_ref_id         BIGINT,
                                      title                   VARCHAR(200),
                                      content                 TEXT NOT NULL,
                                      channel                 VARCHAR(32) NOT NULL,             -- APP/SMS/WECHAT
                                      status                  VARCHAR(32) NOT NULL DEFAULT 'PENDING', -- PENDING/SENT/FAILED
                                      scheduled_at            TIMESTAMPTZ,
                                      sent_at                 TIMESTAMPTZ,
                                      created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
