package xenosoft.imldintelligence.modules.clinical.internal.model;

import lombok.Data;

@Data
public class GeneticReport {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long encounterId;
    private String reportSource;   // 检测机构
    private java.time.LocalDate reportDate;
    private Long fileId;
    private String parseStatus;    // PENDING/PARSED/FAILED/MANUAL
    private String summary;
    private String conclusion;     // POSITIVE/NEGATIVE/UNCERTAIN
    private java.time.OffsetDateTime createdAt;
}
/**
 * Schema:
 * CREATE TABLE genetic_report (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     patient_id              BIGINT NOT NULL REFERENCES patient(id),
 *     encounter_id            BIGINT REFERENCES encounter(id),
 *     report_source           VARCHAR(200),                     -- 检测机构
 *     report_date             DATE,
 *     file_id                 BIGINT REFERENCES file_asset(id),
 *     parse_status            VARCHAR(32) NOT NULL DEFAULT 'PENDING', -- PENDING/PARSED/FAILED/MANUAL
 *     summary                 TEXT,
 *     conclusion              VARCHAR(64),                      -- POSITIVE/NEGATIVE/UNCERTAIN
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
 * );
 */
