package xenosoft.imldintelligence.modules.clinical.internal.model;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.Data;

@Data
public class IndicatorMapper {
    private Long id;
    private Long tenantId;
    private String sourceSystem;            // LIS/HIS/CSV
    private String sourceCode;
    private String sourceName;
    private String targetIndicatorCode;     // 关联的系统统一指标编码
    private String unitConversionExpr;      // 单位换算表达式
    private JsonNode qualityRule;             // 质控规则，JSON格式
    private String status;
    private java.time.OffsetDateTime createdAt;
}
/**
 * Schema:
 * CREATE TABLE indicator_mapping (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     source_system           VARCHAR(32) NOT NULL,             -- LIS/HIS/CSV
 *     source_code             VARCHAR(128) NOT NULL,
 *     source_name             VARCHAR(200),
 *     target_indicator_code   VARCHAR(64) NOT NULL REFERENCES indicator_dict(code),
 *     unit_conversion_expr    VARCHAR(200),                     -- 单位换算表达式
 *     quality_rule            JSONB,                            -- 质控规则
 *     status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     UNIQUE (tenant_id, source_system, source_code)
 * );
 */