package xenosoft.imldintelligence.modules.clinical.internal.model;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.Data;

@Data
public class LabResult {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long encounterId;
    private String indicatorCode;
    private Double valueNumeric;
    private String valueText;
    private String unit;
    private Double referenceLow;
    private Double referenceHigh;
    private String abnormalFlag;       // H/L/N/CRITICAL
    private String sourceType;        // MANUAL/LIS_IMPORT/FILE_UPLOAD
    private JsonNode rawData;           // raw data in JSON string
    private java.time.OffsetDateTime collectedAt;
    private java.time.OffsetDateTime createdAt;
}
/**
 * Schema:
 * CREATE TABLE lab_result (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     patient_id              BIGINT NOT NULL REFERENCES patient(id),
 *     encounter_id            BIGINT REFERENCES encounter(id),
 *     indicator_code          VARCHAR(64) NOT NULL REFERENCES indicator_dict(code),
 *     value_numeric           NUMERIC(18,6),
 *     value_text              VARCHAR(200),
 *     unit                    VARCHAR(32),
 *     reference_low           NUMERIC(18,6),
 *     reference_high          NUMERIC(18,6),
 *     abnormal_flag           VARCHAR(16),                      -- H/L/N/CRITICAL
 *     source_type             VARCHAR(32) NOT NULL,             -- MANUAL/LIS_IMPORT/FILE_UPLOAD
 *     raw_data                JSONB,                            -- raw data
 *     collected_at            TIMESTAMPTZ,
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
 * );
 */
