package xenosoft.imldintelligence.module.careplan.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "alert_event", autoResultMap = true)
public class AlertEvent{
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long carePlanId;
    private String triggerType;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode triggerDetail;
    private String severity;
    private String status;
    private Long assignedTo;
    private java.time.OffsetDateTime createdAt;
    private java.time.OffsetDateTime resolvedAt;
    private String resolutionNote;
}
/**
 * CREATE TABLE alert_event (
                             id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                             patient_id              BIGINT NOT NULL REFERENCES patient(id),
                             care_plan_id            BIGINT REFERENCES care_plan(id),
                             trigger_type            VARCHAR(32) NOT NULL,             -- THRESHOLD/MISSED_FOLLOWUP/CUSTOM
                             trigger_detail          JSONB,
                             severity                VARCHAR(16) NOT NULL,             -- INFO/WARNING/CRITICAL
                             status                  VARCHAR(32) NOT NULL,             -- OPEN/ACKNOWLEDGED/RESOLVED/IGNORED
                             assigned_to             BIGINT REFERENCES user_account(id),
                             created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                             resolved_at             TIMESTAMPTZ,
                             resolution_note         TEXT
);
 */