package xenosoft.imldintelligence.module.careplan.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@lombok.Data
@TableName("alert_action")
public class AlertAction {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long alertId;
    private String actionType;
    private Long actionBy;
    private String actionNote;
    private java.time.OffsetDateTime createdAt;
    
}
/**
 * CREATE TABLE alert_action (
                              id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                              alert_id                BIGINT NOT NULL REFERENCES alert_event(id),
                              action_type             VARCHAR(32) NOT NULL,             -- ACK/RESOLVE/IGNORE/ESCALATE
                              action_by               BIGINT REFERENCES user_account(id),
                              action_note             TEXT,
                              created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */