package xenosoft.imldintelligence.module.careplan.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "care_plan_template", autoResultMap = true)
public class CarePlanTemplate {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private String templateCode;
    private String templateName;
    private String diseaseCode;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode planSchema;
    private String status;
    private Integer versionNo;
    private Long createdBy;
    private java.time.OffsetDateTime createdAt;  
}
/**
 * CREATE TABLE care_plan_template (
                                    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                    template_code           VARCHAR(64) NOT NULL,
                                    template_name           VARCHAR(100) NOT NULL,
                                    disease_code            VARCHAR(64),
                                    plan_schema             JSONB NOT NULL,                   -- 任务频次/阈值/提醒策略
                                    status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                    version_no              INT NOT NULL DEFAULT 1,
                                    created_by              BIGINT REFERENCES user_account(id),
                                    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                    UNIQUE (tenant_id, template_code, version_no)
);
 */