package xenosoft.imldintelligence.module.careplan.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@lombok.Data
@TableName("followup_task")
public class FollowupTask {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long carePlanId;
    private Long patientId;
    private String taskType;
    private java.time.OffsetDateTime scheduledAt;
    private String channel;
    private String status;
    private Long assignedTo;
    private java.time.OffsetDateTime completedAt;
    private String resultSummary;
    private java.time.OffsetDateTime createdAt;
}
/**
 * CREATE TABLE followup_task (
                               id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                               care_plan_id            BIGINT NOT NULL REFERENCES care_plan(id),
                               patient_id              BIGINT NOT NULL REFERENCES patient(id),
                               task_type               VARCHAR(32) NOT NULL,             -- LAB_CHECK/CLINIC_VISIT/PHONE_CALL/QUESTIONNAIRE
                               scheduled_at            TIMESTAMPTZ NOT NULL,
                               channel                 VARCHAR(32) NOT NULL,             -- APP/SMS/PHONE/WECHAT/ONSITE
                               status                  VARCHAR(32) NOT NULL,             -- PENDING/NOTIFIED/COMPLETED/MISSED/CANCELLED
                               assigned_to             BIGINT REFERENCES user_account(id),
                               completed_at            TIMESTAMPTZ,
                               result_summary          TEXT,
                               created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
