package xenosoft.imldintelligence.module.careplan.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "patient_reported_data", autoResultMap = true)
public class PatientReportedData {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long carePlanId;
    private String indicatorCode;
    private Double valueNumeric;
    private String valueText;
    private String source;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode deviceInfo;
    private java.time.OffsetDateTime recordedAt;
    private java.time.OffsetDateTime createdAt;
}
/**
 * CREATE TABLE patient_reported_data (
                                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                       patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                       care_plan_id            BIGINT REFERENCES care_plan(id),
                                       indicator_code          VARCHAR(64) NOT NULL,             -- 可复用 indicator_dict.code
                                       value_numeric           NUMERIC(18,6),
                                       value_text              VARCHAR(200),
                                       source                  VARCHAR(32) NOT NULL,             -- MANUAL/DEVICE_SYNC
                                       device_info             JSONB,
                                       recorded_at             TIMESTAMPTZ NOT NULL,
                                       created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
