package xenosoft.imldintelligence.shared.model;

@lombok.Data
public class FileAsset {
    private Long id;
    private Long tenantId;
    private String bizType;
    private String fileName;
    private String fileExt;
    private String mimeType;
    private Long fileSize;
    private String storageProvider;
    private String storageKey;
    private String sha256;
    private Long uploadedBy;
    private java.time.OffsetDateTime uploadedAt;
}
/**
 * CREATE TABLE file_asset (
                            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                            biz_type                VARCHAR(32) NOT NULL,             -- GENETIC_REPORT/REPORT_SIGN/IMAGING_REPORT/ATTACHMENT
                            file_name               VARCHAR(255) NOT NULL,
                            file_ext                VARCHAR(16),
                            mime_type               VARCHAR(100),
                            file_size               BIGINT,
                            storage_provider        VARCHAR(32) NOT NULL,             -- MINIO/OSS/NAS
                            storage_key             VARCHAR(500) NOT NULL,
                            sha256                  VARCHAR(64),
                            uploaded_by             BIGINT REFERENCES user_account(id),
                            uploaded_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */