CREATE TABLE IF NOT EXISTS tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(64) NOT NULL UNIQUE,
    tenant_name VARCHAR(200) NOT NULL,
    deploy_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    user_no VARCHAR(64) NOT NULL,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    user_type VARCHAR(32) NOT NULL,
    dept_name VARCHAR(100),
    mobile_encrypted VARCHAR(255),
    email VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, user_no),
    UNIQUE (tenant_id, username),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    description TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, role_code),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    permission_code VARCHAR(128) NOT NULL,
    permission_name VARCHAR(200) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    action VARCHAR(32) NOT NULL,
    description TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, permission_code),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS role_permission_rel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted_by BIGINT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (role_id, permission_id),
    FOREIGN KEY (tenant_id, role_id) REFERENCES role(tenant_id, id),
    FOREIGN KEY (tenant_id, permission_id) REFERENCES permission(tenant_id, id),
    FOREIGN KEY (tenant_id, granted_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS user_role_rel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    granted_by BIGINT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, role_id),
    FOREIGN KEY (tenant_id, user_id) REFERENCES user_account(tenant_id, id),
    FOREIGN KEY (tenant_id, role_id) REFERENCES role(tenant_id, id),
    FOREIGN KEY (tenant_id, granted_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS abac_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    policy_code VARCHAR(64) NOT NULL,
    policy_name VARCHAR(100) NOT NULL,
    subject_expr JSONB NOT NULL,
    resource_expr JSONB NOT NULL,
    action_expr JSONB NOT NULL,
    effect VARCHAR(16) NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, policy_code)
);

CREATE TABLE IF NOT EXISTS patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_no VARCHAR(64) NOT NULL,
    patient_name VARCHAR(100) NOT NULL,
    gender VARCHAR(16),
    birth_date DATE,
    id_no_encrypted VARCHAR(255),
    mobile_encrypted VARCHAR(255),
    patient_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    source_channel VARCHAR(32) NOT NULL DEFAULT 'HOSPITAL',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, patient_no),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS patient_external_id (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    id_type VARCHAR(32) NOT NULL,
    id_value VARCHAR(128) NOT NULL,
    source_org VARCHAR(200),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id_type, id_value),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS toc_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    toc_uid VARCHAR(64) NOT NULL,
    nickname VARCHAR(100),
    mobile_encrypted VARCHAR(255),
    openid VARCHAR(128),
    unionid VARCHAR(128),
    vip_status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, toc_uid),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS guardian_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    guardian_name VARCHAR(100) NOT NULL,
    guardian_mobile_encrypted VARCHAR(255),
    guardian_id_no_encrypted VARCHAR(255),
    relation_type VARCHAR(32) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS consent_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT,
    toc_user_id BIGINT,
    consent_type VARCHAR(32) NOT NULL,
    consent_version VARCHAR(32) NOT NULL,
    signed_offline BOOLEAN NOT NULL DEFAULT TRUE,
    signed_at TIMESTAMPTZ,
    file_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'VALID',
    remark TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, toc_user_id) REFERENCES toc_user(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS encounter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    encounter_no VARCHAR(64) NOT NULL,
    encounter_type VARCHAR(32) NOT NULL,
    dept_name VARCHAR(100),
    attending_doctor_id BIGINT,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ,
    source_system VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, encounter_no),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, attending_doctor_id) REFERENCES user_account(tenant_id, id)
);

CREATE OR REPLACE VIEW v_user_effective_roles AS
SELECT
    urr.tenant_id,
    urr.user_id,
    r.role_code,
    r.role_name
FROM user_role_rel urr
JOIN role r
    ON r.tenant_id = urr.tenant_id
   AND r.id = urr.role_id
WHERE r.status = 'ACTIVE';

CREATE OR REPLACE VIEW v_user_subject AS
SELECT
    ua.id AS user_id,
    ua.tenant_id,
    ua.user_type,
    ua.dept_name,
    ARRAY_AGG(r.role_code) FILTER (WHERE r.role_code IS NOT NULL) AS role_codes
FROM user_account ua
LEFT JOIN user_role_rel urr
    ON urr.tenant_id = ua.tenant_id
   AND urr.user_id = ua.id
LEFT JOIN role r
    ON r.tenant_id = urr.tenant_id
   AND r.id = urr.role_id
   AND r.status = 'ACTIVE'
WHERE ua.status = 'ACTIVE'
GROUP BY ua.id, ua.tenant_id, ua.user_type, ua.dept_name;

CREATE OR REPLACE VIEW v_user_permissions AS
SELECT DISTINCT
    urr.tenant_id,
    urr.user_id,
    p.permission_code,
    p.resource_type,
    p.action
FROM user_role_rel urr
JOIN role r
    ON r.tenant_id = urr.tenant_id
   AND r.id = urr.role_id
   AND r.status = 'ACTIVE'
JOIN role_permission_rel rpr
    ON rpr.tenant_id = r.tenant_id
   AND rpr.role_id = r.id
JOIN permission p
    ON p.tenant_id = rpr.tenant_id
   AND p.id = rpr.permission_id
   AND p.status = 'ACTIVE';

CREATE OR REPLACE VIEW v_role_permissions AS
SELECT
    r.tenant_id,
    r.id AS role_id,
    r.role_code,
    p.permission_code,
    p.resource_type,
    p.action
FROM role r
JOIN role_permission_rel rpr
    ON rpr.tenant_id = r.tenant_id
   AND rpr.role_id = r.id
JOIN permission p
    ON p.tenant_id = rpr.tenant_id
   AND p.id = rpr.permission_id
WHERE r.status = 'ACTIVE'
  AND p.status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS idx_permission_tenant_resource_action
    ON permission (tenant_id, resource_type, action);

CREATE INDEX IF NOT EXISTS idx_role_permission_rel_tenant_role
    ON role_permission_rel (tenant_id, role_id);

CREATE INDEX IF NOT EXISTS idx_role_permission_rel_tenant_permission
    ON role_permission_rel (tenant_id, permission_id);

CREATE INDEX IF NOT EXISTS idx_patient_tenant_status
    ON patient (tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_patient_external_id_tenant_patient
    ON patient_external_id (tenant_id, patient_id);

CREATE INDEX IF NOT EXISTS idx_encounter_tenant_patient_time
    ON encounter (tenant_id, patient_id, start_at DESC);
