CREATE TABLE IF NOT EXISTS model_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    model_code VARCHAR(64) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    model_type VARCHAR(32) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    provider VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    released_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, model_code, model_version),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS diagnosis_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    doctor_id BIGINT,
    triggered_by VARCHAR(32) NOT NULL,
    model_registry_id BIGINT,
    input_snapshot JSONB NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, encounter_id) REFERENCES encounter(tenant_id, id),
    FOREIGN KEY (tenant_id, doctor_id) REFERENCES user_account(tenant_id, id),
    FOREIGN KEY (tenant_id, model_registry_id) REFERENCES model_registry(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS diagnosis_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    session_id BIGINT NOT NULL,
    disease_code VARCHAR(64) NOT NULL,
    disease_name VARCHAR(200) NOT NULL,
    confidence NUMERIC(8, 6),
    rank_no INT NOT NULL,
    risk_level VARCHAR(32),
    evidence_json JSONB,
    is_display_to_patient BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, session_id) REFERENCES diagnosis_session(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS diagnosis_recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    session_id BIGINT NOT NULL,
    rec_type VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, session_id) REFERENCES diagnosis_session(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS doctor_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    session_id BIGINT NOT NULL,
    result_id BIGINT,
    doctor_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    modified_value JSONB,
    reject_reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, session_id) REFERENCES diagnosis_session(tenant_id, id),
    FOREIGN KEY (tenant_id, result_id) REFERENCES diagnosis_result(tenant_id, id),
    FOREIGN KEY (tenant_id, doctor_id) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS report_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(100) NOT NULL,
    disease_code VARCHAR(64),
    department VARCHAR(100),
    template_schema JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    version_no INT NOT NULL DEFAULT 1,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, template_code, version_no),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, created_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    session_id BIGINT,
    template_id BIGINT,
    report_no VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_version INT NOT NULL DEFAULT 1,
    signed_by BIGINT,
    signed_at TIMESTAMPTZ,
    signature_data JSONB,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, report_no),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, encounter_id) REFERENCES encounter(tenant_id, id),
    FOREIGN KEY (tenant_id, session_id) REFERENCES diagnosis_session(tenant_id, id),
    FOREIGN KEY (tenant_id, template_id) REFERENCES report_template(tenant_id, id),
    FOREIGN KEY (tenant_id, signed_by) REFERENCES user_account(tenant_id, id),
    FOREIGN KEY (tenant_id, created_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS report_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    report_id BIGINT NOT NULL,
    version_num INT NOT NULL,
    content_snapshot JSONB NOT NULL,
    change_summary TEXT,
    changed_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (report_id, version_num),
    FOREIGN KEY (tenant_id, report_id) REFERENCES report(tenant_id, id),
    FOREIGN KEY (tenant_id, changed_by) REFERENCES user_account(tenant_id, id)
);

CREATE INDEX IF NOT EXISTS idx_diag_session_tenant_patient_time
    ON diagnosis_session (tenant_id, patient_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_diag_result_tenant_session_rank
    ON diagnosis_result (tenant_id, session_id, rank_no);

CREATE INDEX IF NOT EXISTS idx_report_tenant_patient_time
    ON report (tenant_id, patient_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_report_version_tenant_report_ver
    ON report_version (tenant_id, report_id, version_num DESC);
