CREATE TABLE IF NOT EXISTS care_plan_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(100) NOT NULL,
    disease_code VARCHAR(64),
    plan_schema JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    version_no INT NOT NULL DEFAULT 1,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, template_code, version_no),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, created_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS care_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    disease_code VARCHAR(64) NOT NULL,
    plan_type VARCHAR(32) NOT NULL,
    enrollment_type VARCHAR(32) NOT NULL,
    template_id BIGINT,
    status VARCHAR(32) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, template_id) REFERENCES care_plan_template(tenant_id, id),
    FOREIGN KEY (tenant_id, created_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS followup_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    care_plan_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    channel VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    assigned_to BIGINT,
    completed_at TIMESTAMPTZ,
    result_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, care_plan_id) REFERENCES care_plan(tenant_id, id),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, assigned_to) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS patient_reported_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    care_plan_id BIGINT,
    indicator_code VARCHAR(64) NOT NULL,
    value_numeric NUMERIC(18, 6),
    value_text VARCHAR(200),
    source VARCHAR(32) NOT NULL,
    device_info JSONB,
    recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, care_plan_id) REFERENCES care_plan(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS alert_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    care_plan_id BIGINT,
    trigger_type VARCHAR(32) NOT NULL,
    trigger_detail JSONB,
    severity VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    assigned_to BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    resolution_note TEXT,
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, care_plan_id) REFERENCES care_plan(tenant_id, id),
    FOREIGN KEY (tenant_id, assigned_to) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS alert_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    alert_id BIGINT NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    action_by BIGINT,
    action_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, alert_id) REFERENCES alert_event(tenant_id, id),
    FOREIGN KEY (tenant_id, action_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS questionnaire (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    questionnaire_code VARCHAR(64) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    disease_scope VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    version_no INT NOT NULL DEFAULT 1,
    validated_flag BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, questionnaire_code, version_no),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS questionnaire_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    questionnaire_id BIGINT NOT NULL,
    question_no VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    options_json JSONB,
    scoring_rule_json JSONB,
    sort_order INT NOT NULL,
    required_flag BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (questionnaire_id, question_no),
    FOREIGN KEY (tenant_id, questionnaire_id) REFERENCES questionnaire(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS questionnaire_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    questionnaire_id BIGINT NOT NULL,
    toc_user_id BIGINT NOT NULL,
    response_no VARCHAR(64) NOT NULL,
    risk_score NUMERIC(10, 4),
    risk_level VARCHAR(32),
    suggestion TEXT,
    can_show_patient BOOLEAN NOT NULL DEFAULT TRUE,
    data_consent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    UNIQUE (tenant_id, response_no),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, questionnaire_id) REFERENCES questionnaire(tenant_id, id),
    FOREIGN KEY (tenant_id, toc_user_id) REFERENCES toc_user(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS toc_clinical_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    response_id BIGINT NOT NULL,
    patient_id BIGINT,
    transfer_status VARCHAR(32) NOT NULL,
    approved_by BIGINT,
    approved_at TIMESTAMPTZ,
    transfer_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, response_id) REFERENCES questionnaire_response(tenant_id, id),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, approved_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS vip_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    plan_code VARCHAR(64) NOT NULL,
    plan_name VARCHAR(100) NOT NULL,
    duration_days INT NOT NULL,
    price_amount NUMERIC(12, 2) NOT NULL,
    currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, plan_code),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS vip_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    order_no VARCHAR(64) NOT NULL,
    toc_user_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    order_status VARCHAR(32) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    paid_at TIMESTAMPTZ,
    channel VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, order_no),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, toc_user_id) REFERENCES toc_user(tenant_id, id),
    FOREIGN KEY (tenant_id, plan_id) REFERENCES vip_plan(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS vip_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    toc_user_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    subscription_status VARCHAR(32) NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, toc_user_id) REFERENCES toc_user(tenant_id, id),
    FOREIGN KEY (tenant_id, plan_id) REFERENCES vip_plan(tenant_id, id),
    FOREIGN KEY (tenant_id, order_id) REFERENCES vip_order(tenant_id, id)
);

CREATE INDEX IF NOT EXISTS idx_followup_tenant_patient_status_time
    ON followup_task (tenant_id, patient_id, status, scheduled_at);

CREATE INDEX IF NOT EXISTS idx_alert_tenant_patient_status_time
    ON alert_event (tenant_id, patient_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_questionnaire_response_tenant_user_time
    ON questionnaire_response (tenant_id, toc_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_vip_order_tenant_user_time
    ON vip_order (tenant_id, toc_user_id, created_at DESC);
