CREATE TABLE IF NOT EXISTS notification_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    biz_type VARCHAR(32) NOT NULL,
    biz_id VARCHAR(64),
    receiver_type VARCHAR(32) NOT NULL,
    receiver_ref_id BIGINT,
    title VARCHAR(200),
    content TEXT NOT NULL,
    channel VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    scheduled_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS notification_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    message_id BIGINT NOT NULL,
    provider_name VARCHAR(64),
    provider_message_id VARCHAR(128),
    delivery_status VARCHAR(32) NOT NULL,
    fail_reason VARCHAR(255),
    callback_payload JSONB,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, message_id) REFERENCES notification_message(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS integration_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    job_no VARCHAR(64) NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    biz_type VARCHAR(32) NOT NULL,
    request_payload JSONB,
    response_payload JSONB,
    status VARCHAR(32) NOT NULL,
    error_message TEXT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, job_no)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    user_id BIGINT,
    user_role VARCHAR(64),
    action VARCHAR(32) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(128),
    before_data JSONB,
    after_data JSONB,
    ip_address VARCHAR(64),
    device_info VARCHAR(255),
    app_version VARCHAR(64),
    trace_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, user_id) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS sensitive_data_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    user_id BIGINT,
    sensitive_type VARCHAR(32) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(128),
    access_reason VARCHAR(255),
    access_result VARCHAR(32) NOT NULL,
    ip_address VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, user_id) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS model_invocation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    session_id BIGINT,
    model_registry_id BIGINT,
    provider VARCHAR(64),
    request_id VARCHAR(128),
    input_digest VARCHAR(128),
    output_digest VARCHAR(128),
    latency_ms INT,
    token_in INT,
    token_out INT,
    cost_amount NUMERIC(12, 4),
    status VARCHAR(32) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, session_id) REFERENCES diagnosis_session(tenant_id, id),
    FOREIGN KEY (tenant_id, model_registry_id) REFERENCES model_registry(tenant_id, id)
);

CREATE INDEX IF NOT EXISTS idx_notification_tenant_receiver_status
    ON notification_message (tenant_id, receiver_type, receiver_ref_id, status);

CREATE INDEX IF NOT EXISTS idx_integration_job_tenant_source_time
    ON integration_job (tenant_id, source_system, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_log_tenant_resource_time
    ON audit_log (tenant_id, resource_type, resource_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sensitive_access_tenant_resource_time
    ON sensitive_data_access_log (tenant_id, resource_type, resource_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_model_invocation_tenant_session_time
    ON model_invocation_log (tenant_id, session_id, created_at DESC);
