CREATE TABLE IF NOT EXISTS community_board (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    board_code VARCHAR(64) NOT NULL,
    board_name VARCHAR(200) NOT NULL,
    description TEXT,
    disease_scope VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, board_code),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS community_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    board_id BIGINT NOT NULL,
    author_toc_user_id BIGINT NOT NULL,
    author_display_name VARCHAR(100),
    anonymous_flag BOOLEAN NOT NULL DEFAULT FALSE,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    content_format VARCHAR(32) NOT NULL DEFAULT 'TEXT',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    pinned_flag BOOLEAN NOT NULL DEFAULT FALSE,
    like_count INT NOT NULL DEFAULT 0,
    comment_count INT NOT NULL DEFAULT 0,
    report_count INT NOT NULL DEFAULT 0,
    last_activity_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    review_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, board_id) REFERENCES community_board(tenant_id, id),
    FOREIGN KEY (tenant_id, author_toc_user_id) REFERENCES toc_user(tenant_id, id),
    FOREIGN KEY (tenant_id, reviewed_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS community_post_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    post_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    author_toc_user_id BIGINT NOT NULL,
    author_display_name VARCHAR(100),
    anonymous_flag BOOLEAN NOT NULL DEFAULT FALSE,
    content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, post_id) REFERENCES community_post(tenant_id, id),
    FOREIGN KEY (tenant_id, parent_comment_id) REFERENCES community_post_comment(tenant_id, id),
    FOREIGN KEY (tenant_id, author_toc_user_id) REFERENCES toc_user(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS community_post_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    post_id BIGINT NOT NULL,
    toc_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, post_id, toc_user_id),
    FOREIGN KEY (tenant_id, post_id) REFERENCES community_post(tenant_id, id),
    FOREIGN KEY (tenant_id, toc_user_id) REFERENCES toc_user(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS community_post_bookmark (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    post_id BIGINT NOT NULL,
    toc_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, post_id, toc_user_id),
    FOREIGN KEY (tenant_id, post_id) REFERENCES community_post(tenant_id, id),
    FOREIGN KEY (tenant_id, toc_user_id) REFERENCES toc_user(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS community_content_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    reporter_toc_user_id BIGINT NOT NULL,
    post_id BIGINT,
    comment_id BIGINT,
    reason_code VARCHAR(32) NOT NULL,
    reason_text TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    handled_by BIGINT,
    handled_at TIMESTAMPTZ,
    result_action VARCHAR(32),
    result_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CHECK ((post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL)),
    FOREIGN KEY (tenant_id, reporter_toc_user_id) REFERENCES toc_user(tenant_id, id),
    FOREIGN KEY (tenant_id, post_id) REFERENCES community_post(tenant_id, id),
    FOREIGN KEY (tenant_id, comment_id) REFERENCES community_post_comment(tenant_id, id),
    FOREIGN KEY (tenant_id, handled_by) REFERENCES user_account(tenant_id, id)
);

CREATE INDEX IF NOT EXISTS idx_community_board_tenant_status_sort
    ON community_board (tenant_id, status, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_community_post_tenant_board_status_time
    ON community_post (tenant_id, board_id, status, pinned_flag DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_community_post_tenant_author_time
    ON community_post (tenant_id, author_toc_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_community_comment_tenant_post_time
    ON community_post_comment (tenant_id, post_id, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_community_like_tenant_user_time
    ON community_post_like (tenant_id, toc_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_community_bookmark_tenant_user_time
    ON community_post_bookmark (tenant_id, toc_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_community_report_tenant_status_time
    ON community_content_report (tenant_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_community_report_tenant_post
    ON community_content_report (tenant_id, post_id);

CREATE INDEX IF NOT EXISTS idx_community_report_tenant_comment
    ON community_content_report (tenant_id, comment_id);

-- Community post auto-moderation audit fields (append-only ALTERs for compatibility)
ALTER TABLE community_post
    ADD COLUMN IF NOT EXISTS auto_review_status VARCHAR(32) NOT NULL DEFAULT 'UNSET';

ALTER TABLE community_post
    ADD COLUMN IF NOT EXISTS auto_review_provider VARCHAR(32);

ALTER TABLE community_post
    ADD COLUMN IF NOT EXISTS auto_review_reason TEXT;

ALTER TABLE community_post
    ADD COLUMN IF NOT EXISTS auto_review_at TIMESTAMPTZ;
