-- Identity
COMMENT ON TABLE tenant IS '租户主表，承载机构身份、部署模式与租户级启停状态。';
COMMENT ON COLUMN tenant.id IS '租户主键。';
COMMENT ON COLUMN tenant.tenant_code IS '租户编码，跨系统稳定标识。';
COMMENT ON COLUMN tenant.tenant_name IS '租户名称，通常为医院或机构名。';
COMMENT ON COLUMN tenant.deploy_mode IS '部署模式，如 SAAS 或 PRIVATE_HOSPITAL。';
COMMENT ON COLUMN tenant.status IS '租户状态，如 ACTIVE 或 INACTIVE。';
COMMENT ON COLUMN tenant.created_at IS '创建时间。';
COMMENT ON COLUMN tenant.updated_at IS '最后更新时间。';

COMMENT ON TABLE user_account IS '院内用户账号表，用于医护、运营与管理人员身份认证。';
COMMENT ON COLUMN user_account.id IS '用户主键。';
COMMENT ON COLUMN user_account.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN user_account.user_no IS '院内工号或账号编码。';
COMMENT ON COLUMN user_account.username IS '登录用户名。';
COMMENT ON COLUMN user_account.password_hash IS '密码哈希，禁止存储明文口令。';
COMMENT ON COLUMN user_account.display_name IS '展示名称。';
COMMENT ON COLUMN user_account.user_type IS '用户类型，如 DOCTOR、NURSE、ADMIN。';
COMMENT ON COLUMN user_account.dept_name IS '所属科室名称。';
COMMENT ON COLUMN user_account.mobile_encrypted IS '加密后的手机号。';
COMMENT ON COLUMN user_account.email IS '邮箱地址。';
COMMENT ON COLUMN user_account.status IS '账号状态。';
COMMENT ON COLUMN user_account.last_login_at IS '最近一次登录时间。';
COMMENT ON COLUMN user_account.created_at IS '创建时间。';
COMMENT ON COLUMN user_account.updated_at IS '最后更新时间。';

COMMENT ON TABLE role IS '角色定义表，承载 RBAC 角色目录。';
COMMENT ON COLUMN role.id IS '角色主键。';
COMMENT ON COLUMN role.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN role.role_code IS '角色编码。';
COMMENT ON COLUMN role.role_name IS '角色名称。';
COMMENT ON COLUMN role.description IS '角色说明。';
COMMENT ON COLUMN role.status IS '角色状态。';
COMMENT ON COLUMN role.created_at IS '创建时间。';

COMMENT ON TABLE permission IS '权限定义表，描述资源与动作级授权点。';
COMMENT ON COLUMN permission.id IS '权限主键。';
COMMENT ON COLUMN permission.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN permission.permission_code IS '权限编码。';
COMMENT ON COLUMN permission.permission_name IS '权限名称。';
COMMENT ON COLUMN permission.resource_type IS '资源类型，如 PATIENT、REPORT。';
COMMENT ON COLUMN permission.action IS '动作类型，如 READ、UPDATE、EXPORT。';
COMMENT ON COLUMN permission.description IS '权限说明。';
COMMENT ON COLUMN permission.status IS '权限状态。';
COMMENT ON COLUMN permission.created_at IS '创建时间。';

COMMENT ON TABLE role_permission_rel IS '角色与权限关系表，定义角色拥有哪些授权点。';
COMMENT ON COLUMN role_permission_rel.id IS '关系主键。';
COMMENT ON COLUMN role_permission_rel.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN role_permission_rel.role_id IS '角色 ID。';
COMMENT ON COLUMN role_permission_rel.permission_id IS '权限 ID。';
COMMENT ON COLUMN role_permission_rel.granted_by IS '授权人用户 ID。';
COMMENT ON COLUMN role_permission_rel.granted_at IS '授权时间。';

COMMENT ON TABLE user_role_rel IS '用户与角色关系表，定义用户当前具备的角色。';
COMMENT ON COLUMN user_role_rel.id IS '关系主键。';
COMMENT ON COLUMN user_role_rel.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN user_role_rel.user_id IS '用户 ID。';
COMMENT ON COLUMN user_role_rel.role_id IS '角色 ID。';
COMMENT ON COLUMN user_role_rel.granted_by IS '授权人用户 ID。';
COMMENT ON COLUMN user_role_rel.granted_at IS '授权时间。';

COMMENT ON TABLE abac_policy IS 'ABAC 策略表，定义主体、资源、动作三元条件与效应。';
COMMENT ON COLUMN abac_policy.id IS '策略主键。';
COMMENT ON COLUMN abac_policy.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN abac_policy.policy_code IS '策略编码。';
COMMENT ON COLUMN abac_policy.policy_name IS '策略名称。';
COMMENT ON COLUMN abac_policy.subject_expr IS '主体条件表达式 JSON。';
COMMENT ON COLUMN abac_policy.resource_expr IS '资源条件表达式 JSON。';
COMMENT ON COLUMN abac_policy.action_expr IS '动作条件表达式 JSON。';
COMMENT ON COLUMN abac_policy.effect IS '策略效果，如 ALLOW 或 DENY。';
COMMENT ON COLUMN abac_policy.priority IS '策略优先级，值越小优先级越高。';
COMMENT ON COLUMN abac_policy.status IS '策略状态。';
COMMENT ON COLUMN abac_policy.created_at IS '创建时间。';

COMMENT ON TABLE patient IS '患者主索引表，承载院内患者基础身份。';
COMMENT ON COLUMN patient.id IS '患者主键。';
COMMENT ON COLUMN patient.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN patient.patient_no IS '院内患者编号。';
COMMENT ON COLUMN patient.patient_name IS '患者姓名。';
COMMENT ON COLUMN patient.gender IS '性别。';
COMMENT ON COLUMN patient.birth_date IS '出生日期。';
COMMENT ON COLUMN patient.id_no_encrypted IS '加密后的证件号。';
COMMENT ON COLUMN patient.mobile_encrypted IS '加密后的手机号。';
COMMENT ON COLUMN patient.patient_type IS '患者类型，如门诊或住院。';
COMMENT ON COLUMN patient.status IS '患者状态。';
COMMENT ON COLUMN patient.source_channel IS '来源渠道，如 HOSPITAL。';
COMMENT ON COLUMN patient.created_at IS '创建时间。';
COMMENT ON COLUMN patient.updated_at IS '最后更新时间。';

COMMENT ON TABLE patient_external_id IS '患者外部标识映射表，用于 EMPI、MRN 等外部编号对照。';
COMMENT ON COLUMN patient_external_id.id IS '外部标识主键。';
COMMENT ON COLUMN patient_external_id.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN patient_external_id.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN patient_external_id.id_type IS '外部标识类型。';
COMMENT ON COLUMN patient_external_id.id_value IS '外部标识值。';
COMMENT ON COLUMN patient_external_id.source_org IS '来源机构或来源系统。';
COMMENT ON COLUMN patient_external_id.is_primary IS '是否主标识。';
COMMENT ON COLUMN patient_external_id.created_at IS '创建时间。';

COMMENT ON TABLE toc_user IS '院外 ToC 用户表，承载患者端账号身份。';
COMMENT ON COLUMN toc_user.id IS 'ToC 用户主键。';
COMMENT ON COLUMN toc_user.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN toc_user.toc_uid IS 'ToC 体系唯一标识。';
COMMENT ON COLUMN toc_user.nickname IS '昵称。';
COMMENT ON COLUMN toc_user.mobile_encrypted IS '加密后的手机号。';
COMMENT ON COLUMN toc_user.openid IS '第三方平台 OpenID。';
COMMENT ON COLUMN toc_user.unionid IS '第三方生态统一 ID。';
COMMENT ON COLUMN toc_user.vip_status IS '会员状态。';
COMMENT ON COLUMN toc_user.status IS '账号状态。';
COMMENT ON COLUMN toc_user.created_at IS '创建时间。';
COMMENT ON COLUMN toc_user.updated_at IS '最后更新时间。';

COMMENT ON TABLE guardian_relation IS '患者监护人关系表。';
COMMENT ON COLUMN guardian_relation.id IS '监护关系主键。';
COMMENT ON COLUMN guardian_relation.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN guardian_relation.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN guardian_relation.guardian_name IS '监护人姓名。';
COMMENT ON COLUMN guardian_relation.guardian_mobile_encrypted IS '加密后的监护人手机号。';
COMMENT ON COLUMN guardian_relation.guardian_id_no_encrypted IS '加密后的监护人证件号。';
COMMENT ON COLUMN guardian_relation.relation_type IS '与患者的关系类型。';
COMMENT ON COLUMN guardian_relation.is_primary IS '是否主要监护人。';
COMMENT ON COLUMN guardian_relation.status IS '关系状态。';
COMMENT ON COLUMN guardian_relation.created_at IS '创建时间。';

COMMENT ON TABLE consent_record IS '知情同意记录表，用于院内与院外授权留痕。';
COMMENT ON COLUMN consent_record.id IS '同意记录主键。';
COMMENT ON COLUMN consent_record.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN consent_record.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN consent_record.toc_user_id IS '关联 ToC 用户 ID。';
COMMENT ON COLUMN consent_record.consent_type IS '同意类型，如 CLINICAL、DATA_TRANSFER。';
COMMENT ON COLUMN consent_record.consent_version IS '同意书版本。';
COMMENT ON COLUMN consent_record.signed_offline IS '是否线下签署。';
COMMENT ON COLUMN consent_record.signed_at IS '签署时间。';
COMMENT ON COLUMN consent_record.file_id IS '签署文件资产 ID。';
COMMENT ON COLUMN consent_record.status IS '同意状态，如 VALID、REVOKED。';
COMMENT ON COLUMN consent_record.remark IS '补充说明。';
COMMENT ON COLUMN consent_record.created_at IS '创建时间。';

COMMENT ON TABLE encounter IS '就诊记录表，连接患者、医生与一次具体就诊。';
COMMENT ON COLUMN encounter.id IS '就诊主键。';
COMMENT ON COLUMN encounter.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN encounter.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN encounter.encounter_no IS '就诊号。';
COMMENT ON COLUMN encounter.encounter_type IS '就诊类型。';
COMMENT ON COLUMN encounter.dept_name IS '就诊科室。';
COMMENT ON COLUMN encounter.attending_doctor_id IS '接诊医生 ID。';
COMMENT ON COLUMN encounter.start_at IS '开始时间。';
COMMENT ON COLUMN encounter.end_at IS '结束时间。';
COMMENT ON COLUMN encounter.source_system IS '来源系统，如 HIS 或 EMR。';
COMMENT ON COLUMN encounter.created_at IS '创建时间。';

COMMENT ON VIEW v_user_effective_roles IS '有效角色视图，仅暴露启用角色。';
COMMENT ON COLUMN v_user_effective_roles.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN v_user_effective_roles.user_id IS '用户 ID。';
COMMENT ON COLUMN v_user_effective_roles.role_code IS '角色编码。';
COMMENT ON COLUMN v_user_effective_roles.role_name IS '角色名称。';

COMMENT ON VIEW v_user_subject IS '用户主体视图，聚合用户类型、科室与有效角色集合。';
COMMENT ON COLUMN v_user_subject.user_id IS '用户 ID。';
COMMENT ON COLUMN v_user_subject.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN v_user_subject.user_type IS '用户类型。';
COMMENT ON COLUMN v_user_subject.dept_name IS '用户所属科室。';
COMMENT ON COLUMN v_user_subject.role_codes IS '有效角色编码数组。';

COMMENT ON VIEW v_user_permissions IS '用户权限视图，展开用户经角色继承到的权限点。';
COMMENT ON COLUMN v_user_permissions.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN v_user_permissions.user_id IS '用户 ID。';
COMMENT ON COLUMN v_user_permissions.permission_code IS '权限编码。';
COMMENT ON COLUMN v_user_permissions.resource_type IS '资源类型。';
COMMENT ON COLUMN v_user_permissions.action IS '动作类型。';

COMMENT ON VIEW v_role_permissions IS '角色权限视图，展开角色绑定的权限点。';
COMMENT ON COLUMN v_role_permissions.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN v_role_permissions.role_id IS '角色 ID。';
COMMENT ON COLUMN v_role_permissions.role_code IS '角色编码。';
COMMENT ON COLUMN v_role_permissions.permission_code IS '权限编码。';
COMMENT ON COLUMN v_role_permissions.resource_type IS '资源类型。';
COMMENT ON COLUMN v_role_permissions.action IS '动作类型。';

COMMENT ON INDEX idx_permission_tenant_resource_action IS '按租户、资源类型、动作查询权限定义。';
COMMENT ON INDEX idx_role_permission_rel_tenant_role IS '按租户和角色查询角色权限关系。';
COMMENT ON INDEX idx_role_permission_rel_tenant_permission IS '按租户和权限查询角色权限关系。';
COMMENT ON INDEX idx_patient_tenant_status IS '按租户和状态检索患者。';
COMMENT ON INDEX idx_patient_external_id_tenant_patient IS '按租户和患者查询外部标识。';
COMMENT ON INDEX idx_encounter_tenant_patient_time IS '按租户、患者和就诊时间倒序查询就诊。';
-- Clinical
COMMENT ON TABLE indicator_dict IS '临床指标字典表，统一定义院内外指标编码与参考信息。';
COMMENT ON COLUMN indicator_dict.code IS '统一指标编码。';
COMMENT ON COLUMN indicator_dict.indicator_name IS '指标名称。';
COMMENT ON COLUMN indicator_dict.category IS '指标分类。';
COMMENT ON COLUMN indicator_dict.data_type IS '数据类型，如 NUMERIC、TEXT、ENUM。';
COMMENT ON COLUMN indicator_dict.default_unit IS '默认单位。';
COMMENT ON COLUMN indicator_dict.loinc_code IS '标准 LOINC 编码。';
COMMENT ON COLUMN indicator_dict.normal_low IS '参考下限。';
COMMENT ON COLUMN indicator_dict.normal_high IS '参考上限。';
COMMENT ON COLUMN indicator_dict.status IS '指标状态。';
COMMENT ON COLUMN indicator_dict.created_at IS '创建时间。';

COMMENT ON TABLE indicator_mapping IS '外部指标映射表，将 LIS/HIS 原始编码映射到统一指标。';
COMMENT ON COLUMN indicator_mapping.id IS '映射主键。';
COMMENT ON COLUMN indicator_mapping.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN indicator_mapping.source_system IS '来源系统。';
COMMENT ON COLUMN indicator_mapping.source_code IS '来源指标编码。';
COMMENT ON COLUMN indicator_mapping.source_name IS '来源指标名称。';
COMMENT ON COLUMN indicator_mapping.target_indicator_code IS '映射后的统一指标编码。';
COMMENT ON COLUMN indicator_mapping.unit_conversion_expr IS '单位换算表达式。';
COMMENT ON COLUMN indicator_mapping.quality_rule IS '质控规则 JSON。';
COMMENT ON COLUMN indicator_mapping.status IS '映射状态。';
COMMENT ON COLUMN indicator_mapping.created_at IS '创建时间。';

COMMENT ON TABLE lab_result IS '检验结果表。';
COMMENT ON COLUMN lab_result.id IS '检验结果主键。';
COMMENT ON COLUMN lab_result.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN lab_result.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN lab_result.encounter_id IS '关联就诊 ID。';
COMMENT ON COLUMN lab_result.indicator_code IS '统一指标编码。';
COMMENT ON COLUMN lab_result.value_numeric IS '数值结果。';
COMMENT ON COLUMN lab_result.value_text IS '文本结果。';
COMMENT ON COLUMN lab_result.unit IS '结果单位。';
COMMENT ON COLUMN lab_result.reference_low IS '参考下限。';
COMMENT ON COLUMN lab_result.reference_high IS '参考上限。';
COMMENT ON COLUMN lab_result.abnormal_flag IS '异常标记。';
COMMENT ON COLUMN lab_result.source_type IS '来源类型。';
COMMENT ON COLUMN lab_result.raw_data IS '原始结果载荷 JSON。';
COMMENT ON COLUMN lab_result.collected_at IS '采样时间。';
COMMENT ON COLUMN lab_result.created_at IS '创建时间。';

COMMENT ON TABLE clinical_history_entry IS '病史条目表，沉淀既往史、家族史、过敏史等结构化内容。';
COMMENT ON COLUMN clinical_history_entry.id IS '病史条目主键。';
COMMENT ON COLUMN clinical_history_entry.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN clinical_history_entry.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN clinical_history_entry.encounter_id IS '关联就诊 ID。';
COMMENT ON COLUMN clinical_history_entry.history_type IS '病史类型。';
COMMENT ON COLUMN clinical_history_entry.template_code IS '病史模板编码。';
COMMENT ON COLUMN clinical_history_entry.content_json IS '结构化病史内容 JSON。';
COMMENT ON COLUMN clinical_history_entry.source_type IS '采集来源。';
COMMENT ON COLUMN clinical_history_entry.recorded_by IS '记录人用户 ID。';
COMMENT ON COLUMN clinical_history_entry.recorded_at IS '记录时间。';
COMMENT ON COLUMN clinical_history_entry.created_at IS '创建时间。';

COMMENT ON TABLE file_asset IS '文件资产表，登记报告、附件与扫描件等文件元数据。';
COMMENT ON COLUMN file_asset.id IS '文件资产主键。';
COMMENT ON COLUMN file_asset.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN file_asset.biz_type IS '业务类型。';
COMMENT ON COLUMN file_asset.file_name IS '原始文件名。';
COMMENT ON COLUMN file_asset.file_ext IS '文件扩展名。';
COMMENT ON COLUMN file_asset.mime_type IS 'MIME 类型。';
COMMENT ON COLUMN file_asset.file_size IS '文件大小，单位字节。';
COMMENT ON COLUMN file_asset.storage_provider IS '存储提供方。';
COMMENT ON COLUMN file_asset.storage_key IS '对象存储键或路径。';
COMMENT ON COLUMN file_asset.sha256 IS '文件内容 SHA-256 摘要。';
COMMENT ON COLUMN file_asset.uploaded_by IS '上传人用户 ID。';
COMMENT ON COLUMN file_asset.uploaded_at IS '上传时间。';

COMMENT ON TABLE genetic_report IS '基因报告主表。';
COMMENT ON COLUMN genetic_report.id IS '基因报告主键。';
COMMENT ON COLUMN genetic_report.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN genetic_report.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN genetic_report.encounter_id IS '关联就诊 ID。';
COMMENT ON COLUMN genetic_report.report_source IS '报告来源机构。';
COMMENT ON COLUMN genetic_report.report_date IS '报告日期。';
COMMENT ON COLUMN genetic_report.file_id IS '报告文件资产 ID。';
COMMENT ON COLUMN genetic_report.parse_status IS '解析状态。';
COMMENT ON COLUMN genetic_report.summary IS '摘要。';
COMMENT ON COLUMN genetic_report.conclusion IS '结论分级。';
COMMENT ON COLUMN genetic_report.created_at IS '创建时间。';

COMMENT ON TABLE genetic_variant IS '基因变异明细表。';
COMMENT ON COLUMN genetic_variant.id IS '变异主键。';
COMMENT ON COLUMN genetic_variant.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN genetic_variant.report_id IS '所属基因报告 ID。';
COMMENT ON COLUMN genetic_variant.gene IS '基因名称。';
COMMENT ON COLUMN genetic_variant.chromosome IS '染色体位置。';
COMMENT ON COLUMN genetic_variant.position IS '基因组坐标。';
COMMENT ON COLUMN genetic_variant.ref_allele IS '参考等位基因。';
COMMENT ON COLUMN genetic_variant.alt_allele IS '变异等位基因。';
COMMENT ON COLUMN genetic_variant.variant_type IS '变异类型。';
COMMENT ON COLUMN genetic_variant.zygosity IS '合子状态。';
COMMENT ON COLUMN genetic_variant.classification IS '临床分类。';
COMMENT ON COLUMN genetic_variant.hgvs_c IS 'HGVS c. 表达式。';
COMMENT ON COLUMN genetic_variant.hgvs_p IS 'HGVS p. 表达式。';
COMMENT ON COLUMN genetic_variant.evidence IS '证据说明。';
COMMENT ON COLUMN genetic_variant.source_type IS '来源类型。';
COMMENT ON COLUMN genetic_variant.created_at IS '创建时间。';

COMMENT ON TABLE imaging_report IS '影像报告表。';
COMMENT ON COLUMN imaging_report.id IS '影像报告主键。';
COMMENT ON COLUMN imaging_report.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN imaging_report.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN imaging_report.encounter_id IS '关联就诊 ID。';
COMMENT ON COLUMN imaging_report.modality IS '检查模态。';
COMMENT ON COLUMN imaging_report.report_text IS '结构化或文本化报告内容。';
COMMENT ON COLUMN imaging_report.file_id IS '报告文件资产 ID。';
COMMENT ON COLUMN imaging_report.source_system IS '来源系统。';
COMMENT ON COLUMN imaging_report.examined_at IS '检查时间。';
COMMENT ON COLUMN imaging_report.created_at IS '创建时间。';

COMMENT ON INDEX idx_lab_result_tenant_patient_indicator_time IS '按租户、患者、指标和采样时间查询检验结果。';
COMMENT ON INDEX idx_lab_result_tenant_encounter IS '按租户和就诊查询检验结果。';
COMMENT ON INDEX idx_genetic_report_tenant_patient_time IS '按租户、患者和报告日期查询基因报告。';
COMMENT ON INDEX idx_genetic_variant_tenant_report_gene IS '按租户、报告和基因查询变异。';
-- Diagnosis & Report
COMMENT ON TABLE model_registry IS '模型注册表，记录规则、ML、NLP、LLM 等模型版本。';
COMMENT ON COLUMN model_registry.id IS '模型主键。';
COMMENT ON COLUMN model_registry.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN model_registry.model_code IS '模型编码。';
COMMENT ON COLUMN model_registry.model_name IS '模型名称。';
COMMENT ON COLUMN model_registry.model_type IS '模型类型。';
COMMENT ON COLUMN model_registry.model_version IS '模型版本。';
COMMENT ON COLUMN model_registry.provider IS '模型提供方。';
COMMENT ON COLUMN model_registry.status IS '模型状态。';
COMMENT ON COLUMN model_registry.released_at IS '发布时间。';
COMMENT ON COLUMN model_registry.created_at IS '创建时间。';

COMMENT ON TABLE diagnosis_session IS '诊断会话表，记录一次模型诊断执行过程。';
COMMENT ON COLUMN diagnosis_session.id IS '诊断会话主键。';
COMMENT ON COLUMN diagnosis_session.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN diagnosis_session.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN diagnosis_session.encounter_id IS '关联就诊 ID。';
COMMENT ON COLUMN diagnosis_session.doctor_id IS '发起或关联医生 ID。';
COMMENT ON COLUMN diagnosis_session.triggered_by IS '触发方式。';
COMMENT ON COLUMN diagnosis_session.model_registry_id IS '使用的模型注册 ID。';
COMMENT ON COLUMN diagnosis_session.input_snapshot IS '输入快照 JSON。';
COMMENT ON COLUMN diagnosis_session.status IS '会话状态。';
COMMENT ON COLUMN diagnosis_session.started_at IS '开始时间。';
COMMENT ON COLUMN diagnosis_session.completed_at IS '完成时间。';
COMMENT ON COLUMN diagnosis_session.created_at IS '创建时间。';

COMMENT ON TABLE diagnosis_result IS '诊断结果表。';
COMMENT ON COLUMN diagnosis_result.id IS '诊断结果主键。';
COMMENT ON COLUMN diagnosis_result.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN diagnosis_result.session_id IS '所属诊断会话 ID。';
COMMENT ON COLUMN diagnosis_result.disease_code IS '疾病编码。';
COMMENT ON COLUMN diagnosis_result.disease_name IS '疾病名称。';
COMMENT ON COLUMN diagnosis_result.confidence IS '置信度。';
COMMENT ON COLUMN diagnosis_result.rank_no IS '排序位次。';
COMMENT ON COLUMN diagnosis_result.risk_level IS '风险等级。';
COMMENT ON COLUMN diagnosis_result.evidence_json IS '证据 JSON。';
COMMENT ON COLUMN diagnosis_result.is_display_to_patient IS '是否允许对患者可见。';
COMMENT ON COLUMN diagnosis_result.created_at IS '创建时间。';

COMMENT ON TABLE diagnosis_recommendation IS '诊断建议表。';
COMMENT ON COLUMN diagnosis_recommendation.id IS '建议主键。';
COMMENT ON COLUMN diagnosis_recommendation.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN diagnosis_recommendation.session_id IS '所属诊断会话 ID。';
COMMENT ON COLUMN diagnosis_recommendation.rec_type IS '建议类型。';
COMMENT ON COLUMN diagnosis_recommendation.content IS '建议内容。';
COMMENT ON COLUMN diagnosis_recommendation.priority IS '建议优先级。';
COMMENT ON COLUMN diagnosis_recommendation.reason IS '建议原因。';
COMMENT ON COLUMN diagnosis_recommendation.created_at IS '创建时间。';

COMMENT ON TABLE doctor_feedback IS '医生反馈表，用于接受、修改或驳回模型结果。';
COMMENT ON COLUMN doctor_feedback.id IS '反馈主键。';
COMMENT ON COLUMN doctor_feedback.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN doctor_feedback.session_id IS '所属诊断会话 ID。';
COMMENT ON COLUMN doctor_feedback.result_id IS '关联诊断结果 ID。';
COMMENT ON COLUMN doctor_feedback.doctor_id IS '反馈医生 ID。';
COMMENT ON COLUMN doctor_feedback.action IS '反馈动作。';
COMMENT ON COLUMN doctor_feedback.modified_value IS '修改后的内容 JSON。';
COMMENT ON COLUMN doctor_feedback.reject_reason IS '驳回原因。';
COMMENT ON COLUMN doctor_feedback.created_at IS '创建时间。';

COMMENT ON TABLE report_template IS '报告模板表，定义报告结构与版本。';
COMMENT ON COLUMN report_template.id IS '模板主键。';
COMMENT ON COLUMN report_template.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN report_template.template_code IS '模板编码。';
COMMENT ON COLUMN report_template.template_name IS '模板名称。';
COMMENT ON COLUMN report_template.disease_code IS '适用疾病编码。';
COMMENT ON COLUMN report_template.department IS '适用科室。';
COMMENT ON COLUMN report_template.template_schema IS '模板结构 JSON。';
COMMENT ON COLUMN report_template.status IS '模板状态。';
COMMENT ON COLUMN report_template.version_no IS '版本号。';
COMMENT ON COLUMN report_template.created_by IS '创建人用户 ID。';
COMMENT ON COLUMN report_template.created_at IS '创建时间。';

COMMENT ON TABLE report IS '诊断报告主表。';
COMMENT ON COLUMN report.id IS '报告主键。';
COMMENT ON COLUMN report.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN report.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN report.encounter_id IS '关联就诊 ID。';
COMMENT ON COLUMN report.session_id IS '关联诊断会话 ID。';
COMMENT ON COLUMN report.template_id IS '报告模板 ID。';
COMMENT ON COLUMN report.report_no IS '报告编号。';
COMMENT ON COLUMN report.status IS '报告状态。';
COMMENT ON COLUMN report.current_version IS '当前版本号。';
COMMENT ON COLUMN report.signed_by IS '签署人用户 ID。';
COMMENT ON COLUMN report.signed_at IS '签署时间。';
COMMENT ON COLUMN report.signature_data IS '签名元数据 JSON。';
COMMENT ON COLUMN report.created_by IS '创建人用户 ID。';
COMMENT ON COLUMN report.created_at IS '创建时间。';
COMMENT ON COLUMN report.updated_at IS '最后更新时间。';

COMMENT ON TABLE report_version IS '报告版本快照表。';
COMMENT ON COLUMN report_version.id IS '版本主键。';
COMMENT ON COLUMN report_version.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN report_version.report_id IS '所属报告 ID。';
COMMENT ON COLUMN report_version.version_num IS '版本号。';
COMMENT ON COLUMN report_version.content_snapshot IS '版本内容快照 JSON。';
COMMENT ON COLUMN report_version.change_summary IS '版本变更摘要。';
COMMENT ON COLUMN report_version.changed_by IS '变更人用户 ID。';
COMMENT ON COLUMN report_version.created_at IS '创建时间。';

COMMENT ON INDEX idx_diag_session_tenant_patient_time IS '按租户、患者和开始时间查询诊断会话。';
COMMENT ON INDEX idx_diag_result_tenant_session_rank IS '按租户、会话和排序位次查询诊断结果。';
COMMENT ON INDEX idx_report_tenant_patient_time IS '按租户、患者和创建时间查询报告。';
COMMENT ON INDEX idx_report_version_tenant_report_ver IS '按租户、报告和版本号倒序查询报告版本。';
-- Careplan / Screening / Payment
COMMENT ON TABLE care_plan_template IS '随访计划模板表。';
COMMENT ON COLUMN care_plan_template.id IS '模板主键。';
COMMENT ON COLUMN care_plan_template.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN care_plan_template.template_code IS '模板编码。';
COMMENT ON COLUMN care_plan_template.template_name IS '模板名称。';
COMMENT ON COLUMN care_plan_template.disease_code IS '适用疾病编码。';
COMMENT ON COLUMN care_plan_template.plan_schema IS '计划结构 JSON。';
COMMENT ON COLUMN care_plan_template.status IS '模板状态。';
COMMENT ON COLUMN care_plan_template.version_no IS '版本号。';
COMMENT ON COLUMN care_plan_template.created_by IS '创建人用户 ID。';
COMMENT ON COLUMN care_plan_template.created_at IS '创建时间。';

COMMENT ON TABLE care_plan IS '患者照护计划主表。';
COMMENT ON COLUMN care_plan.id IS '照护计划主键。';
COMMENT ON COLUMN care_plan.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN care_plan.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN care_plan.disease_code IS '对应疾病编码。';
COMMENT ON COLUMN care_plan.plan_type IS '计划类型，如 STANDARD、VIP。';
COMMENT ON COLUMN care_plan.enrollment_type IS '入组方式。';
COMMENT ON COLUMN care_plan.template_id IS '来源模板 ID。';
COMMENT ON COLUMN care_plan.status IS '计划状态。';
COMMENT ON COLUMN care_plan.start_date IS '开始日期。';
COMMENT ON COLUMN care_plan.end_date IS '结束日期。';
COMMENT ON COLUMN care_plan.created_by IS '创建人用户 ID。';
COMMENT ON COLUMN care_plan.created_at IS '创建时间。';

COMMENT ON TABLE followup_task IS '随访任务表。';
COMMENT ON COLUMN followup_task.id IS '任务主键。';
COMMENT ON COLUMN followup_task.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN followup_task.care_plan_id IS '所属照护计划 ID。';
COMMENT ON COLUMN followup_task.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN followup_task.task_type IS '任务类型。';
COMMENT ON COLUMN followup_task.scheduled_at IS '计划执行时间。';
COMMENT ON COLUMN followup_task.channel IS '执行渠道。';
COMMENT ON COLUMN followup_task.status IS '任务状态。';
COMMENT ON COLUMN followup_task.assigned_to IS '指派用户 ID。';
COMMENT ON COLUMN followup_task.completed_at IS '完成时间。';
COMMENT ON COLUMN followup_task.result_summary IS '结果摘要。';
COMMENT ON COLUMN followup_task.created_at IS '创建时间。';

COMMENT ON TABLE patient_reported_data IS '患者自报数据表。';
COMMENT ON COLUMN patient_reported_data.id IS '自报数据主键。';
COMMENT ON COLUMN patient_reported_data.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN patient_reported_data.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN patient_reported_data.care_plan_id IS '关联照护计划 ID。';
COMMENT ON COLUMN patient_reported_data.indicator_code IS '指标编码。';
COMMENT ON COLUMN patient_reported_data.value_numeric IS '数值型结果。';
COMMENT ON COLUMN patient_reported_data.value_text IS '文本型结果。';
COMMENT ON COLUMN patient_reported_data.source IS '数据来源。';
COMMENT ON COLUMN patient_reported_data.device_info IS '设备信息 JSON。';
COMMENT ON COLUMN patient_reported_data.recorded_at IS '记录时间。';
COMMENT ON COLUMN patient_reported_data.created_at IS '创建时间。';

COMMENT ON TABLE alert_event IS '告警事件表。';
COMMENT ON COLUMN alert_event.id IS '告警主键。';
COMMENT ON COLUMN alert_event.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN alert_event.patient_id IS '关联患者 ID。';
COMMENT ON COLUMN alert_event.care_plan_id IS '关联照护计划 ID。';
COMMENT ON COLUMN alert_event.trigger_type IS '触发类型。';
COMMENT ON COLUMN alert_event.trigger_detail IS '触发明细 JSON。';
COMMENT ON COLUMN alert_event.severity IS '严重程度。';
COMMENT ON COLUMN alert_event.status IS '告警状态。';
COMMENT ON COLUMN alert_event.assigned_to IS '处理人用户 ID。';
COMMENT ON COLUMN alert_event.created_at IS '创建时间。';
COMMENT ON COLUMN alert_event.resolved_at IS '解决时间。';
COMMENT ON COLUMN alert_event.resolution_note IS '处理说明。';

COMMENT ON TABLE alert_action IS '告警处理动作表。';
COMMENT ON COLUMN alert_action.id IS '动作主键。';
COMMENT ON COLUMN alert_action.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN alert_action.alert_id IS '关联告警 ID。';
COMMENT ON COLUMN alert_action.action_type IS '动作类型。';
COMMENT ON COLUMN alert_action.action_by IS '执行人用户 ID。';
COMMENT ON COLUMN alert_action.action_note IS '动作说明。';
COMMENT ON COLUMN alert_action.created_at IS '创建时间。';

COMMENT ON TABLE questionnaire IS '问卷定义表。';
COMMENT ON COLUMN questionnaire.id IS '问卷主键。';
COMMENT ON COLUMN questionnaire.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN questionnaire.questionnaire_code IS '问卷编码。';
COMMENT ON COLUMN questionnaire.title IS '问卷标题。';
COMMENT ON COLUMN questionnaire.description IS '问卷描述。';
COMMENT ON COLUMN questionnaire.disease_scope IS '适用疾病范围。';
COMMENT ON COLUMN questionnaire.status IS '问卷状态。';
COMMENT ON COLUMN questionnaire.version_no IS '版本号。';
COMMENT ON COLUMN questionnaire.validated_flag IS '是否已验证。';
COMMENT ON COLUMN questionnaire.created_at IS '创建时间。';

COMMENT ON TABLE questionnaire_question IS '问卷题目表。';
COMMENT ON COLUMN questionnaire_question.id IS '题目主键。';
COMMENT ON COLUMN questionnaire_question.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN questionnaire_question.questionnaire_id IS '所属问卷 ID。';
COMMENT ON COLUMN questionnaire_question.question_no IS '题号。';
COMMENT ON COLUMN questionnaire_question.content IS '题目内容。';
COMMENT ON COLUMN questionnaire_question.question_type IS '题型。';
COMMENT ON COLUMN questionnaire_question.options_json IS '选项定义 JSON。';
COMMENT ON COLUMN questionnaire_question.scoring_rule_json IS '评分规则 JSON。';
COMMENT ON COLUMN questionnaire_question.sort_order IS '排序号。';
COMMENT ON COLUMN questionnaire_question.required_flag IS '是否必答。';
COMMENT ON COLUMN questionnaire_question.created_at IS '创建时间。';

COMMENT ON TABLE questionnaire_response IS '问卷答卷表。';
COMMENT ON COLUMN questionnaire_response.id IS '答卷主键。';
COMMENT ON COLUMN questionnaire_response.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN questionnaire_response.questionnaire_id IS '所属问卷 ID。';
COMMENT ON COLUMN questionnaire_response.toc_user_id IS '答卷 ToC 用户 ID。';
COMMENT ON COLUMN questionnaire_response.response_no IS '答卷编号。';
COMMENT ON COLUMN questionnaire_response.risk_score IS '风险评分。';
COMMENT ON COLUMN questionnaire_response.risk_level IS '风险等级。';
COMMENT ON COLUMN questionnaire_response.suggestion IS '建议内容。';
COMMENT ON COLUMN questionnaire_response.can_show_patient IS '是否允许对患者展示。';
COMMENT ON COLUMN questionnaire_response.data_consent IS '是否同意数据回流院内。';
COMMENT ON COLUMN questionnaire_response.created_at IS '创建时间。';
COMMENT ON COLUMN questionnaire_response.expires_at IS '过期时间。';

COMMENT ON TABLE toc_clinical_transfer IS 'ToC 问卷结果回流院内临床的转运记录表。';
COMMENT ON COLUMN toc_clinical_transfer.id IS '转运记录主键。';
COMMENT ON COLUMN toc_clinical_transfer.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN toc_clinical_transfer.response_id IS '关联答卷 ID。';
COMMENT ON COLUMN toc_clinical_transfer.patient_id IS '目标患者 ID。';
COMMENT ON COLUMN toc_clinical_transfer.transfer_status IS '转运状态。';
COMMENT ON COLUMN toc_clinical_transfer.approved_by IS '审批人用户 ID。';
COMMENT ON COLUMN toc_clinical_transfer.approved_at IS '审批时间。';
COMMENT ON COLUMN toc_clinical_transfer.transfer_note IS '转运说明。';
COMMENT ON COLUMN toc_clinical_transfer.created_at IS '创建时间。';

COMMENT ON TABLE vip_plan IS 'VIP 订阅计划表。';
COMMENT ON COLUMN vip_plan.id IS '计划主键。';
COMMENT ON COLUMN vip_plan.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN vip_plan.plan_code IS '计划编码。';
COMMENT ON COLUMN vip_plan.plan_name IS '计划名称。';
COMMENT ON COLUMN vip_plan.duration_days IS '有效期天数。';
COMMENT ON COLUMN vip_plan.price_amount IS '价格金额。';
COMMENT ON COLUMN vip_plan.currency_code IS '币种。';
COMMENT ON COLUMN vip_plan.status IS '计划状态。';
COMMENT ON COLUMN vip_plan.created_at IS '创建时间。';

COMMENT ON TABLE vip_order IS 'VIP 订单表。';
COMMENT ON COLUMN vip_order.id IS '订单主键。';
COMMENT ON COLUMN vip_order.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN vip_order.order_no IS '订单号。';
COMMENT ON COLUMN vip_order.toc_user_id IS '下单 ToC 用户 ID。';
COMMENT ON COLUMN vip_order.plan_id IS '购买计划 ID。';
COMMENT ON COLUMN vip_order.order_status IS '订单状态。';
COMMENT ON COLUMN vip_order.amount IS '订单金额。';
COMMENT ON COLUMN vip_order.paid_at IS '支付时间。';
COMMENT ON COLUMN vip_order.channel IS '支付渠道。';
COMMENT ON COLUMN vip_order.created_at IS '创建时间。';

COMMENT ON TABLE vip_subscription IS 'VIP 订阅生效表。';
COMMENT ON COLUMN vip_subscription.id IS '订阅主键。';
COMMENT ON COLUMN vip_subscription.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN vip_subscription.toc_user_id IS '订阅 ToC 用户 ID。';
COMMENT ON COLUMN vip_subscription.plan_id IS '订阅计划 ID。';
COMMENT ON COLUMN vip_subscription.order_id IS '来源订单 ID。';
COMMENT ON COLUMN vip_subscription.subscription_status IS '订阅状态。';
COMMENT ON COLUMN vip_subscription.start_at IS '生效时间。';
COMMENT ON COLUMN vip_subscription.end_at IS '失效时间。';
COMMENT ON COLUMN vip_subscription.created_at IS '创建时间。';

COMMENT ON INDEX idx_followup_tenant_patient_status_time IS '按租户、患者、状态和计划时间查询随访任务。';
COMMENT ON INDEX idx_alert_tenant_patient_status_time IS '按租户、患者、状态和创建时间查询告警。';
COMMENT ON INDEX idx_questionnaire_response_tenant_user_time IS '按租户、ToC 用户和创建时间查询答卷。';
COMMENT ON INDEX idx_vip_order_tenant_user_time IS '按租户、ToC 用户和创建时间查询订单。';
-- Notify / Integration / Audit
COMMENT ON TABLE notification_message IS '通知消息主表。';
COMMENT ON COLUMN notification_message.id IS '通知主键。';
COMMENT ON COLUMN notification_message.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN notification_message.biz_type IS '业务类型。';
COMMENT ON COLUMN notification_message.biz_id IS '业务对象标识。';
COMMENT ON COLUMN notification_message.receiver_type IS '接收者类型。';
COMMENT ON COLUMN notification_message.receiver_ref_id IS '接收者对象 ID。';
COMMENT ON COLUMN notification_message.title IS '通知标题。';
COMMENT ON COLUMN notification_message.content IS '通知内容。';
COMMENT ON COLUMN notification_message.channel IS '发送渠道。';
COMMENT ON COLUMN notification_message.status IS '消息状态。';
COMMENT ON COLUMN notification_message.scheduled_at IS '计划发送时间。';
COMMENT ON COLUMN notification_message.sent_at IS '实际发送时间。';
COMMENT ON COLUMN notification_message.created_at IS '创建时间。';

COMMENT ON TABLE notification_delivery IS '通知投递回执表。';
COMMENT ON COLUMN notification_delivery.id IS '投递记录主键。';
COMMENT ON COLUMN notification_delivery.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN notification_delivery.message_id IS '关联通知消息 ID。';
COMMENT ON COLUMN notification_delivery.provider_name IS '通道提供方名称。';
COMMENT ON COLUMN notification_delivery.provider_message_id IS '提供方消息 ID。';
COMMENT ON COLUMN notification_delivery.delivery_status IS '投递状态。';
COMMENT ON COLUMN notification_delivery.fail_reason IS '失败原因。';
COMMENT ON COLUMN notification_delivery.callback_payload IS '回执载荷 JSON。';
COMMENT ON COLUMN notification_delivery.delivered_at IS '送达时间。';
COMMENT ON COLUMN notification_delivery.created_at IS '创建时间。';

COMMENT ON TABLE integration_job IS '集成作业表，记录与外部系统的数据交换任务。';
COMMENT ON COLUMN integration_job.id IS '作业主键。';
COMMENT ON COLUMN integration_job.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN integration_job.job_no IS '作业编号。';
COMMENT ON COLUMN integration_job.source_system IS '来源或目标系统。';
COMMENT ON COLUMN integration_job.direction IS '流向，如 INBOUND 或 OUTBOUND。';
COMMENT ON COLUMN integration_job.biz_type IS '业务类型。';
COMMENT ON COLUMN integration_job.request_payload IS '请求载荷 JSON。';
COMMENT ON COLUMN integration_job.response_payload IS '响应载荷 JSON。';
COMMENT ON COLUMN integration_job.status IS '作业状态。';
COMMENT ON COLUMN integration_job.error_message IS '错误信息。';
COMMENT ON COLUMN integration_job.started_at IS '开始时间。';
COMMENT ON COLUMN integration_job.finished_at IS '结束时间。';
COMMENT ON COLUMN integration_job.created_at IS '创建时间。';

COMMENT ON TABLE audit_log IS '审计日志表，记录关键操作前后状态与调用上下文。';
COMMENT ON COLUMN audit_log.id IS '审计日志主键。';
COMMENT ON COLUMN audit_log.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN audit_log.user_id IS '操作用户 ID。';
COMMENT ON COLUMN audit_log.user_role IS '操作时角色。';
COMMENT ON COLUMN audit_log.action IS '操作动作。';
COMMENT ON COLUMN audit_log.resource_type IS '资源类型。';
COMMENT ON COLUMN audit_log.resource_id IS '资源标识。';
COMMENT ON COLUMN audit_log.before_data IS '变更前数据快照 JSON。';
COMMENT ON COLUMN audit_log.after_data IS '变更后数据快照 JSON。';
COMMENT ON COLUMN audit_log.ip_address IS '来源 IP。';
COMMENT ON COLUMN audit_log.device_info IS '设备信息。';
COMMENT ON COLUMN audit_log.app_version IS '应用版本。';
COMMENT ON COLUMN audit_log.trace_id IS '追踪链路 ID。';
COMMENT ON COLUMN audit_log.created_at IS '创建时间。';

COMMENT ON TABLE sensitive_data_access_log IS '敏感数据访问日志表，记录高敏数据访问行为与结果。';
COMMENT ON COLUMN sensitive_data_access_log.id IS '日志主键。';
COMMENT ON COLUMN sensitive_data_access_log.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN sensitive_data_access_log.user_id IS '访问用户 ID。';
COMMENT ON COLUMN sensitive_data_access_log.sensitive_type IS '敏感数据类型。';
COMMENT ON COLUMN sensitive_data_access_log.resource_type IS '资源类型。';
COMMENT ON COLUMN sensitive_data_access_log.resource_id IS '资源标识。';
COMMENT ON COLUMN sensitive_data_access_log.access_reason IS '访问原因。';
COMMENT ON COLUMN sensitive_data_access_log.access_result IS '访问结果。';
COMMENT ON COLUMN sensitive_data_access_log.ip_address IS '来源 IP。';
COMMENT ON COLUMN sensitive_data_access_log.created_at IS '创建时间。';

COMMENT ON TABLE model_invocation_log IS '模型调用日志表，记录模型请求摘要、耗时与成本。';
COMMENT ON COLUMN model_invocation_log.id IS '调用日志主键。';
COMMENT ON COLUMN model_invocation_log.tenant_id IS '所属租户 ID。';
COMMENT ON COLUMN model_invocation_log.session_id IS '关联诊断会话 ID。';
COMMENT ON COLUMN model_invocation_log.model_registry_id IS '关联模型注册 ID。';
COMMENT ON COLUMN model_invocation_log.provider IS '模型提供方。';
COMMENT ON COLUMN model_invocation_log.request_id IS '外部请求 ID。';
COMMENT ON COLUMN model_invocation_log.input_digest IS '输入摘要，禁止存原文。';
COMMENT ON COLUMN model_invocation_log.output_digest IS '输出摘要。';
COMMENT ON COLUMN model_invocation_log.latency_ms IS '调用耗时，单位毫秒。';
COMMENT ON COLUMN model_invocation_log.token_in IS '输入 token 数。';
COMMENT ON COLUMN model_invocation_log.token_out IS '输出 token 数。';
COMMENT ON COLUMN model_invocation_log.cost_amount IS '调用成本金额。';
COMMENT ON COLUMN model_invocation_log.status IS '调用状态。';
COMMENT ON COLUMN model_invocation_log.error_message IS '错误信息。';
COMMENT ON COLUMN model_invocation_log.created_at IS '创建时间。';

COMMENT ON INDEX idx_notification_tenant_receiver_status IS '按租户、接收者和状态查询通知消息。';
COMMENT ON INDEX idx_integration_job_tenant_source_time IS '按租户、来源系统和创建时间查询集成作业。';
COMMENT ON INDEX idx_audit_log_tenant_resource_time IS '按租户、资源和时间查询审计日志。';
COMMENT ON INDEX idx_sensitive_access_tenant_resource_time IS '按租户、资源和时间查询敏感访问日志。';
COMMENT ON INDEX idx_model_invocation_tenant_session_time IS '按租户、会话和时间查询模型调用日志。';
