CREATE TABLE IF NOT EXISTS notification_message (
                                      id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                      biz_type                VARCHAR(32) NOT NULL,             -- FOLLOWUP/ALERT/REPORT_READY
                                      biz_id                  VARCHAR(64),
                                      receiver_type           VARCHAR(32) NOT NULL,             -- PATIENT/TOC_USER/GUARDIAN/DOCTOR
                                      receiver_ref_id         BIGINT,
                                      title                   VARCHAR(200),
                                      content                 TEXT NOT NULL,
                                      channel                 VARCHAR(32) NOT NULL,             -- APP/SMS/WECHAT
                                      status                  VARCHAR(32) NOT NULL DEFAULT 'PENDING', -- PENDING/SENT/FAILED
                                      scheduled_at            TIMESTAMPTZ,
                                      sent_at                 TIMESTAMPTZ,
                                      created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notification_delivery (
                                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                       message_id              BIGINT NOT NULL REFERENCES notification_message(id),
                                       provider_name           VARCHAR(64),
                                       provider_message_id     VARCHAR(128),
                                       delivery_status         VARCHAR(32) NOT NULL,             -- ACCEPTED/DELIVERED/FAILED
                                       fail_reason             VARCHAR(255),
                                       callback_payload        JSONB,
                                       delivered_at            TIMESTAMPTZ,
                                       created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS integration_job (
                                 id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                 job_no                  VARCHAR(64) NOT NULL,
                                 source_system           VARCHAR(32) NOT NULL,             -- HIS/LIS/EMR/PACS
                                 direction               VARCHAR(16) NOT NULL,             -- INBOUND/OUTBOUND
                                 biz_type                VARCHAR(32) NOT NULL,             -- PATIENT/LAB/REPORT
                                 request_payload         JSONB,
                                 response_payload        JSONB,
                                 status                  VARCHAR(32) NOT NULL,             -- RUNNING/SUCCESS/FAILED/PARTIAL
                                 error_message           TEXT,
                                 started_at              TIMESTAMPTZ,
                                 finished_at             TIMESTAMPTZ,
                                 created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 UNIQUE (tenant_id, job_no)
);

CREATE TABLE IF NOT EXISTS audit_log (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                           user_id                 BIGINT REFERENCES user_account(id),
                           user_role               VARCHAR(64),
                           action                  VARCHAR(32) NOT NULL,             -- CREATE/READ/UPDATE/DELETE/SIGN/EXPORT
                           resource_type           VARCHAR(64) NOT NULL,             -- PATIENT/REPORT/GENETIC_DATA/QUESTIONNAIRE
                           resource_id             VARCHAR(128),
                           before_data             JSONB,
                           after_data              JSONB,
                           ip_address              VARCHAR(64),
                           device_info             VARCHAR(255),
                           app_version             VARCHAR(64),
                           trace_id                VARCHAR(64),
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sensitive_data_access_log (
                                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                           user_id                 BIGINT REFERENCES user_account(id),
                                           sensitive_type          VARCHAR(32) NOT NULL,             -- GENETIC/ID_CARD/MEDICAL_RECORD
                                           resource_type           VARCHAR(64) NOT NULL,
                                           resource_id             VARCHAR(128),
                                           access_reason           VARCHAR(255),
                                           access_result           VARCHAR(32) NOT NULL,             -- ALLOW/DENY
                                           ip_address              VARCHAR(64),
                                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS model_invocation_log (
                                      id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                      session_id              BIGINT REFERENCES diagnosis_session(id),
                                      model_registry_id       BIGINT REFERENCES model_registry(id),
                                      provider                VARCHAR(64),
                                      request_id              VARCHAR(128),
                                      input_digest            VARCHAR(128),                     -- 输入摘要（避免存明文）
                                      output_digest           VARCHAR(128),                     -- 输出摘要
                                      latency_ms              INT,
                                      token_in                INT,
                                      token_out               INT,
                                      cost_amount             NUMERIC(12,4),
                                      status                  VARCHAR(32) NOT NULL,             -- SUCCESS/FAILED/TIMEOUT
                                      error_message           TEXT,
                                      created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);