CREATE TABLE IF NOT EXISTS tenant (
                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tenant_code             VARCHAR(64) NOT NULL UNIQUE,      -- 机构编码
                        tenant_name             VARCHAR(200) NOT NULL,            -- 医院/机构名称
    deploy_mode             VARCHAR(32) NOT NULL,             -- PRIVATE_HOSPITAL / SAAS
    status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
    );

CREATE TABLE IF NOT EXISTS user_account (
                              id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                              user_no                 VARCHAR(64) NOT NULL,             -- 工号/账号编码
                              username                VARCHAR(100) NOT NULL,
                              password_hash           VARCHAR(255) NOT NULL,
                              display_name            VARCHAR(100) NOT NULL,
                              user_type               VARCHAR(32) NOT NULL,             -- DOCTOR/NURSE/ADMIN/FOLLOWER
                              dept_name               VARCHAR(100),
                              mobile_encrypted        VARCHAR(255),
                              email                   VARCHAR(128),
                              status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                              last_login_at           TIMESTAMPTZ,
                              created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                              updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                              UNIQUE (tenant_id, user_no),
                              UNIQUE (tenant_id, username)
);

CREATE TABLE IF NOT EXISTS role (
                      id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                      role_code               VARCHAR(64) NOT NULL,             -- SYSTEM_ADMIN/DOCTOR/CASE_MANAGER...
                      role_name               VARCHAR(100) NOT NULL,
                      description             TEXT,
                      status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                      created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                      UNIQUE (tenant_id, role_code)
);

CREATE TABLE IF NOT EXISTS user_role_rel (
                               id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                               user_id                 BIGINT NOT NULL REFERENCES user_account(id),
                               role_id                 BIGINT NOT NULL REFERENCES role(id),
                               granted_by              BIGINT REFERENCES user_account(id),
                               granted_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                               UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS abac_policy (
                             id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                             policy_code             VARCHAR(64) NOT NULL,
                             policy_name             VARCHAR(100) NOT NULL,
                             subject_expr            JSONB NOT NULL,                   -- 主体条件（角色/科室/职称）
                             resource_expr           JSONB NOT NULL,                   -- 资源条件（病种/院区/数据级别）
                             action_expr             JSONB NOT NULL,                   -- 行为条件（READ/UPDATE/SIGN...）
                             effect                  VARCHAR(16) NOT NULL,             -- ALLOW / DENY
                             priority                INT NOT NULL DEFAULT 100,
                             status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                             created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                             UNIQUE (tenant_id, policy_code)
);

CREATE TABLE IF NOT EXISTS patient (
                         id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                         patient_no              VARCHAR(64) NOT NULL,             -- 系统内患者编号
                         patient_name            VARCHAR(100) NOT NULL,
                         gender                  VARCHAR(16),
                         birth_date              DATE,
                         id_no_encrypted         VARCHAR(255),
                         mobile_encrypted        VARCHAR(255),
                         patient_type            VARCHAR(32) NOT NULL,             -- INPATIENT/OUTPATIENT
                         status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                         source_channel          VARCHAR(32) NOT NULL DEFAULT 'HOSPITAL', -- HOSPITAL
                         created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                         updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                         UNIQUE (tenant_id, patient_no)
);

CREATE TABLE IF NOT EXISTS patient_external_id (
                                     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                     patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                     id_type                 VARCHAR(32) NOT NULL,             -- EMPI/MRN/ID_CARD/OTHER
                                     id_value                VARCHAR(128) NOT NULL,
                                     source_org              VARCHAR(200),                     -- 来源机构/系统
                                     is_primary              BOOLEAN NOT NULL DEFAULT FALSE,
                                     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                     UNIQUE (tenant_id, id_type, id_value)
);

CREATE TABLE IF NOT EXISTS toc_user (
                          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                          toc_uid                 VARCHAR(64) NOT NULL,             -- ToC 体系唯一ID
                          nickname                VARCHAR(100),
                          mobile_encrypted        VARCHAR(255),
                          openid                  VARCHAR(128),                     -- 小程序/公众号 OpenID
                          unionid                 VARCHAR(128),                     -- 生态统一ID
                          vip_status              VARCHAR(32) NOT NULL DEFAULT 'NORMAL', -- NORMAL/VIP
                          status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                          created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                          updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                          UNIQUE (tenant_id, toc_uid)
);

CREATE TABLE IF NOT EXISTS guardian_relation (
                                   id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                   patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                   guardian_name           VARCHAR(100) NOT NULL,
                                   guardian_mobile_encrypted VARCHAR(255),
                                   guardian_id_no_encrypted VARCHAR(255),
                                   relation_type           VARCHAR(32) NOT NULL,             -- FATHER/MOTHER/LEGAL_GUARDIAN/OTHER
                                   is_primary              BOOLEAN NOT NULL DEFAULT FALSE,
                                   status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                   created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS consent_record (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                patient_id              BIGINT REFERENCES patient(id),
                                toc_user_id             BIGINT REFERENCES toc_user(id),
                                consent_type            VARCHAR(32) NOT NULL,             -- CLINICAL / TOC / GENETIC / DATA_TRANSFER
                                consent_version         VARCHAR(32) NOT NULL,
                                signed_offline          BOOLEAN NOT NULL DEFAULT TRUE,    -- 线下签署
                                signed_at               TIMESTAMPTZ,
                                file_id                 BIGINT,                           -- 关联签署扫描件
                                status                  VARCHAR(32) NOT NULL DEFAULT 'VALID',
                                remark                  TEXT,
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS encounter (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                           patient_id              BIGINT NOT NULL REFERENCES patient(id),
                           encounter_no            VARCHAR(64) NOT NULL,
                           encounter_type          VARCHAR(32) NOT NULL,             -- OUTPATIENT/INPATIENT/EMERGENCY
                           dept_name               VARCHAR(100),
                           attending_doctor_id     BIGINT REFERENCES user_account(id),
                           start_at                TIMESTAMPTZ NOT NULL,
                           end_at                  TIMESTAMPTZ,
                           source_system           VARCHAR(64),                      -- HIS/EMR
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                           UNIQUE (tenant_id, encounter_no)
);

CREATE TABLE IF NOT EXISTS indicator_dict (
                                code                    VARCHAR(64) PRIMARY KEY,          -- 系统统一指标编码
                                indicator_name          VARCHAR(200) NOT NULL,
                                category                VARCHAR(64) NOT NULL,             -- 肝功/代谢/遗传等
                                data_type               VARCHAR(16) NOT NULL,             -- NUMERIC/TEXT/ENUM
                                default_unit            VARCHAR(32),
                                loinc_code              VARCHAR(64),
                                normal_low              NUMERIC(18,6),
                                normal_high             NUMERIC(18,6),
                                status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS indicator_mapping (
                                   id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                   source_system           VARCHAR(32) NOT NULL,             -- LIS/HIS/CSV
                                   source_code             VARCHAR(128) NOT NULL,
                                   source_name             VARCHAR(200),
                                   target_indicator_code   VARCHAR(64) NOT NULL REFERENCES indicator_dict(code),
                                   unit_conversion_expr    VARCHAR(200),                     -- 单位换算表达式
                                   quality_rule            JSONB,                            -- 质控规则
                                   status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                   created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                   UNIQUE (tenant_id, source_system, source_code)
);

CREATE TABLE IF NOT EXISTS lab_result (
                            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                            patient_id              BIGINT NOT NULL REFERENCES patient(id),
                            encounter_id            BIGINT REFERENCES encounter(id),
                            indicator_code          VARCHAR(64) NOT NULL REFERENCES indicator_dict(code),
                            value_numeric           NUMERIC(18,6),
                            value_text              VARCHAR(200),
                            unit                    VARCHAR(32),
                            reference_low           NUMERIC(18,6),
                            reference_high          NUMERIC(18,6),
                            abnormal_flag           VARCHAR(16),                      -- H/L/N/CRITICAL
                            source_type             VARCHAR(32) NOT NULL,             -- MANUAL/LIS_IMPORT/FILE_UPLOAD
                            raw_data                JSONB,                            -- raw data
                            collected_at            TIMESTAMPTZ,
                            created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clinical_history_entry (
                                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                        patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                        encounter_id            BIGINT REFERENCES encounter(id),
                                        history_type            VARCHAR(32) NOT NULL,             -- PAST_HISTORY/FAMILY_HISTORY/ALLERGY/MEDICATION
                                        template_code           VARCHAR(64),                      -- 模板编码
                                        content_json            JSONB NOT NULL,                   -- 结构化表单内容
                                        source_type             VARCHAR(32) NOT NULL DEFAULT 'MANUAL', -- MANUAL/NLP/EMR_IMPORT
                                        recorded_by             BIGINT REFERENCES user_account(id),
                                        recorded_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
                                        created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS file_asset (
                            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                            biz_type                VARCHAR(32) NOT NULL,             -- GENETIC_REPORT/REPORT_SIGN/IMAGING_REPORT/ATTACHMENT
                            file_name               VARCHAR(255) NOT NULL,
                            file_ext                VARCHAR(16),
                            mime_type               VARCHAR(100),
                            file_size               BIGINT,
                            storage_provider        VARCHAR(32) NOT NULL,             -- MINIO/OSS/NAS
                            storage_key             VARCHAR(500) NOT NULL,
                            sha256                  VARCHAR(64),
                            uploaded_by             BIGINT REFERENCES user_account(id),
                            uploaded_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS genetic_report (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                encounter_id            BIGINT REFERENCES encounter(id),
                                report_source           VARCHAR(200),                     -- 检测机构
                                report_date             DATE,
                                file_id                 BIGINT REFERENCES file_asset(id),
                                parse_status            VARCHAR(32) NOT NULL DEFAULT 'PENDING', -- PENDING/PARSED/FAILED/MANUAL
                                summary                 TEXT,
                                conclusion              VARCHAR(64),                      -- POSITIVE/NEGATIVE/UNCERTAIN
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS genetic_variant (
                                 id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                 report_id               BIGINT NOT NULL REFERENCES genetic_report(id),
                                 gene                    VARCHAR(64) NOT NULL,
                                 chromosome              VARCHAR(16),
                                 position                BIGINT,
                                 ref_allele              VARCHAR(32),
                                 alt_allele              VARCHAR(32),
                                 variant_type            VARCHAR(32),                      -- SNV/INDEL/CNV
                                 zygosity                VARCHAR(32),                      -- HOM/HET/COMPOUND_HET
                                 classification          VARCHAR(64),                      -- PATHOGENIC/LIKELY_PATHOGENIC/VUS/BENIGN
                                 hgvs_c                  VARCHAR(255),
                                 hgvs_p                  VARCHAR(255),
                                 evidence                TEXT,
                                 source_type             VARCHAR(32) NOT NULL DEFAULT 'PARSED',
                                 created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS imaging_report (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                encounter_id            BIGINT REFERENCES encounter(id),
                                modality                VARCHAR(32),                      -- US/CT/MRI/PATHOLOGY
                                report_text             TEXT NOT NULL,                    -- 仅存结构化文字报告
                                file_id                 BIGINT REFERENCES file_asset(id), -- 报告附件（PDF等）
                                source_system           VARCHAR(32) NOT NULL DEFAULT 'PACS',
                                examined_at             TIMESTAMPTZ,
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);