CREATE TABLE IF NOT EXISTS model_registry (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                model_code              VARCHAR(64) NOT NULL,
                                model_name              VARCHAR(100) NOT NULL,
                                model_type              VARCHAR(32) NOT NULL,             -- RULE/ML/NLP/LLM
                                model_version           VARCHAR(64) NOT NULL,
                                provider                VARCHAR(64),                      -- LOCAL/OPENAI/THIRD_PARTY
                                status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                released_at             TIMESTAMPTZ,
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                UNIQUE (tenant_id, model_code, model_version)
);

CREATE TABLE IF NOT EXISTS diagnosis_session (
                                   id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                   patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                   encounter_id            BIGINT REFERENCES encounter(id),
                                   doctor_id               BIGINT REFERENCES user_account(id),
                                   triggered_by            VARCHAR(32) NOT NULL,             -- MANUAL/AUTO
                                   model_registry_id       BIGINT REFERENCES model_registry(id),
                                   input_snapshot          JSONB NOT NULL,                   -- 输入快照
                                   status                  VARCHAR(32) NOT NULL,             -- RUNNING/COMPLETED/FAILED
                                   started_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                   completed_at            TIMESTAMPTZ,
                                   created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS diagnosis_result (
                                  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                  session_id              BIGINT NOT NULL REFERENCES diagnosis_session(id),
                                  disease_code            VARCHAR(64) NOT NULL,
                                  disease_name            VARCHAR(200) NOT NULL,
                                  confidence              NUMERIC(8,6),
                                  rank_no                 INT NOT NULL,
                                  risk_level              VARCHAR(32),                      -- LOW/MEDIUM/HIGH
                                  evidence_json           JSONB,
                                  is_display_to_patient   BOOLEAN NOT NULL DEFAULT FALSE,   -- 中间结果默认不对患者展示
                                  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS diagnosis_recommendation (
                                          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                          session_id              BIGINT NOT NULL REFERENCES diagnosis_session(id),
                                          rec_type                VARCHAR(32) NOT NULL,             -- EXAM/LAB/GENETIC/FOLLOWUP/REFERRAL
                                          content                 TEXT NOT NULL,
                                          priority                INT NOT NULL DEFAULT 100,
                                          reason                  TEXT,
                                          created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS doctor_feedback (
                                 id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                 session_id              BIGINT NOT NULL REFERENCES diagnosis_session(id),
                                 result_id               BIGINT REFERENCES diagnosis_result(id),
                                 doctor_id               BIGINT NOT NULL REFERENCES user_account(id),
                                 action                  VARCHAR(32) NOT NULL,             -- ACCEPT/MODIFY/REJECT/IGNORE
                                 modified_value          JSONB,
                                 reject_reason           VARCHAR(255),
                                 created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS report_template (
                                 id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                 template_code           VARCHAR(64) NOT NULL,
                                 template_name           VARCHAR(100) NOT NULL,
                                 disease_code            VARCHAR(64),                      -- 可空：通用模板
                                 department              VARCHAR(100),                     -- 可空：通用模板
                                 template_schema         JSONB NOT NULL,                   -- 模板结构定义
                                 status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                 version_no              INT NOT NULL DEFAULT 1,
                                 created_by              BIGINT REFERENCES user_account(id),
                                 created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 UNIQUE (tenant_id, template_code, version_no)
);

CREATE TABLE IF NOT EXISTS report (
                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                        patient_id              BIGINT NOT NULL REFERENCES patient(id),
                        encounter_id            BIGINT REFERENCES encounter(id),
                        session_id              BIGINT REFERENCES diagnosis_session(id),
                        template_id             BIGINT REFERENCES report_template(id),
                        report_no               VARCHAR(64) NOT NULL,
                        status                  VARCHAR(32) NOT NULL,             -- DRAFT/PENDING_REVIEW/APPROVED/SIGNED/ARCHIVED
                        current_version         INT NOT NULL DEFAULT 1,
                        signed_by               BIGINT REFERENCES user_account(id),
                        signed_at               TIMESTAMPTZ,
                        signature_data          JSONB,                            -- 兼容普通签名/CA签名元数据
                        created_by              BIGINT REFERENCES user_account(id),
                        created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                        updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                        UNIQUE (tenant_id, report_no)
);

CREATE TABLE IF NOT EXISTS report_version (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                report_id               BIGINT NOT NULL REFERENCES report(id),
                                version_num             INT NOT NULL,
                                content_snapshot        JSONB NOT NULL,                   -- 全量快照
                                change_summary          TEXT,
                                changed_by              BIGINT REFERENCES user_account(id),
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                UNIQUE (report_id, version_num)
);