CREATE TABLE IF NOT EXISTS care_plan_template (
                                    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                    template_code           VARCHAR(64) NOT NULL,
                                    template_name           VARCHAR(100) NOT NULL,
                                    disease_code            VARCHAR(64),
                                    plan_schema             JSONB NOT NULL,                   -- 任务频次/阈值/提醒策略
                                    status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                    version_no              INT NOT NULL DEFAULT 1,
                                    created_by              BIGINT REFERENCES user_account(id),
                                    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                    UNIQUE (tenant_id, template_code, version_no)
);

CREATE TABLE IF NOT EXISTS care_plan (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                           patient_id              BIGINT NOT NULL REFERENCES patient(id),
                           disease_code            VARCHAR(64) NOT NULL,
                           plan_type               VARCHAR(32) NOT NULL,             -- STANDARD/VIP
                           enrollment_type         VARCHAR(32) NOT NULL,             -- DOCTOR_ASSIGNED/AUTO/PATIENT_PURCHASED
                           template_id             BIGINT REFERENCES care_plan_template(id),
                           status                  VARCHAR(32) NOT NULL,             -- ACTIVE/PAUSED/COMPLETED/TERMINATED
                           start_date              DATE NOT NULL,
                           end_date                DATE,
                           created_by              BIGINT REFERENCES user_account(id),
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS followup_task (
                               id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                               care_plan_id            BIGINT NOT NULL REFERENCES care_plan(id),
                               patient_id              BIGINT NOT NULL REFERENCES patient(id),
                               task_type               VARCHAR(32) NOT NULL,             -- LAB_CHECK/CLINIC_VISIT/PHONE_CALL/QUESTIONNAIRE
                               scheduled_at            TIMESTAMPTZ NOT NULL,
                               channel                 VARCHAR(32) NOT NULL,             -- APP/SMS/PHONE/WECHAT/ONSITE
                               status                  VARCHAR(32) NOT NULL,             -- PENDING/NOTIFIED/COMPLETED/MISSED/CANCELLED
                               assigned_to             BIGINT REFERENCES user_account(id),
                               completed_at            TIMESTAMPTZ,
                               result_summary          TEXT,
                               created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS patient_reported_data (
                                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                       patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                       care_plan_id            BIGINT REFERENCES care_plan(id),
                                       indicator_code          VARCHAR(64) NOT NULL,             -- 可复用 indicator_dict.code
                                       value_numeric           NUMERIC(18,6),
                                       value_text              VARCHAR(200),
                                       source                  VARCHAR(32) NOT NULL,             -- MANUAL/DEVICE_SYNC
                                       device_info             JSONB,
                                       recorded_at             TIMESTAMPTZ NOT NULL,
                                       created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS alert_event (
                             id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                             patient_id              BIGINT NOT NULL REFERENCES patient(id),
                             care_plan_id            BIGINT REFERENCES care_plan(id),
                             trigger_type            VARCHAR(32) NOT NULL,             -- THRESHOLD/MISSED_FOLLOWUP/CUSTOM
                             trigger_detail          JSONB,
                             severity                VARCHAR(16) NOT NULL,             -- INFO/WARNING/CRITICAL
                             status                  VARCHAR(32) NOT NULL,             -- OPEN/ACKNOWLEDGED/RESOLVED/IGNORED
                             assigned_to             BIGINT REFERENCES user_account(id),
                             created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                             resolved_at             TIMESTAMPTZ,
                             resolution_note         TEXT
);

CREATE TABLE IF NOT EXISTS alert_action (
                              id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                              alert_id                BIGINT NOT NULL REFERENCES alert_event(id),
                              action_type             VARCHAR(32) NOT NULL,             -- ACK/RESOLVE/IGNORE/ESCALATE
                              action_by               BIGINT REFERENCES user_account(id),
                              action_note             TEXT,
                              created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS questionnaire (
                               id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                               questionnaire_code      VARCHAR(64) NOT NULL,
                               title                   VARCHAR(200) NOT NULL,
                               description             TEXT,
                               disease_scope           VARCHAR(64),
                               status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                               version_no              INT NOT NULL DEFAULT 1,
                               validated_flag          BOOLEAN NOT NULL DEFAULT TRUE,    -- 是否经权威验证
                               created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                               UNIQUE (tenant_id, questionnaire_code, version_no)
);

CREATE TABLE IF NOT EXISTS questionnaire_question (
                                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                        questionnaire_id        BIGINT NOT NULL REFERENCES questionnaire(id),
                                        question_no             VARCHAR(32) NOT NULL,
                                        content                 TEXT NOT NULL,
                                        question_type           VARCHAR(32) NOT NULL,             -- SINGLE/MULTI/INPUT/SCALE
                                        options_json            JSONB,                            -- 选项定义
                                        scoring_rule_json       JSONB,                            -- 计分规则
                                        sort_order              INT NOT NULL,
                                        required_flag           BOOLEAN NOT NULL DEFAULT TRUE,
                                        created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                        UNIQUE (questionnaire_id, question_no)
);

CREATE TABLE IF NOT EXISTS questionnaire_response (
                                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                        questionnaire_id        BIGINT NOT NULL REFERENCES questionnaire(id),
                                        toc_user_id             BIGINT NOT NULL REFERENCES toc_user(id),
                                        response_no             VARCHAR(64) NOT NULL,
                                        risk_score              NUMERIC(10,4),
                                        risk_level              VARCHAR(32),
                                        suggestion              TEXT,
                                        can_show_patient        BOOLEAN NOT NULL DEFAULT TRUE,
                                        data_consent            BOOLEAN NOT NULL DEFAULT FALSE,   -- 是否授权流转院内
                                        created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                        expires_at              TIMESTAMPTZ,
                                        UNIQUE (tenant_id, response_no)
);

CREATE TABLE IF NOT EXISTS toc_clinical_transfer (
                                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                       response_id             BIGINT NOT NULL REFERENCES questionnaire_response(id),
                                       patient_id              BIGINT REFERENCES patient(id),
                                       transfer_status         VARCHAR(32) NOT NULL,             -- PENDING/APPROVED/REJECTED/COMPLETED
                                       approved_by             BIGINT REFERENCES user_account(id),
                                       approved_at             TIMESTAMPTZ,
                                       transfer_note           TEXT,
                                       created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vip_plan (
                          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                          plan_code               VARCHAR(64) NOT NULL,
                          plan_name               VARCHAR(100) NOT NULL,
                          duration_days           INT NOT NULL,
                          price_amount            NUMERIC(12,2) NOT NULL,
                          currency_code           VARCHAR(16) NOT NULL DEFAULT 'CNY',
                          status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                          created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                          UNIQUE (tenant_id, plan_code)
);

CREATE TABLE IF NOT EXISTS vip_order (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                           order_no                VARCHAR(64) NOT NULL,
                           toc_user_id             BIGINT NOT NULL REFERENCES toc_user(id),
                           plan_id                 BIGINT NOT NULL REFERENCES vip_plan(id),
                           order_status            VARCHAR(32) NOT NULL,             -- CREATED/PAID/CANCELLED/REFUNDED
                           amount                  NUMERIC(12,2) NOT NULL,
                           paid_at                 TIMESTAMPTZ,
                           channel                 VARCHAR(32),                      -- WECHAT/ALIPAY/OTHER
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                           UNIQUE (tenant_id, order_no)
);

CREATE TABLE IF NOT EXISTS vip_subscription (
                                  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                  toc_user_id             BIGINT NOT NULL REFERENCES toc_user(id),
                                  plan_id                 BIGINT NOT NULL REFERENCES vip_plan(id),
                                  order_id                BIGINT NOT NULL REFERENCES vip_order(id),
                                  subscription_status     VARCHAR(32) NOT NULL,             -- ACTIVE/EXPIRED/CANCELLED
                                  start_at                TIMESTAMPTZ NOT NULL,
                                  end_at                  TIMESTAMPTZ NOT NULL,
                                  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
