package xenosoft.imldintelligence.module.clinical.internal.model;

import com.fasterxml.jackson.databind.JsonNode;
@lombok.Data
public class ClinicalHistoryEntry {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long encounterId;
    private String historyType;
    private String templateCode;
    private JsonNode contentJson;
    private String sourceType;
    private Long recordedBy;
    private java.time.OffsetDateTime recordedAt;
    private java.time.OffsetDateTime createdAt;
}

/**
 * Schema:
 * CREATE TABLE clinical_history_entry (
                                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                        patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                        encounter_id            BIGINT REFERENCES encounter(id),
                                        history_type            VARCHAR(32) NOT NULL,             -- PAST_HISTORY/FAMILY_HISTORY/ALLERGY/MEDICATION
                                        template_code           VARCHAR(64),                      -- 模板编码
                                        content_json            JSONB NOT NULL,                   -- 结构化表单内容
                                        source_type             VARCHAR(32) NOT NULL DEFAULT 'MANUAL', -- MANUAL/NLP/EMR_IMPORT
                                        recorded_by             BIGINT REFERENCES user_account(id),
                                        recorded_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
                                        created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */