package xenosoft.imldintelligence.module.clinical.internal.model;

import lombok.Data;

@Data
public class GeneticVariant {
    private Long id;
    private Long tenantId;
    private Long reportId;
    private String gene;
    private String chromosome;
    private Long position;
    private String refAllele;
    private String altAllele;
    private String variantType;       // SNV/INDEL/CNV
    private String zygosity;         // HOM/HET/COMPOUND_HET
    private String classification;   // PATHOGENIC/LIKELY_PATHOGENIC/VUS/BENIGN
    private String hgvsC;
    private String hgvsP;
    private String evidence;
    private String sourceType;       // PARSED/EXTERNAL
    private java.time.OffsetDateTime createdAt;
}
/**
 * Schema:
 * CREATE TABLE genetic_variant (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     report_id               BIGINT NOT NULL REFERENCES genetic_report(id),
 *     gene                    VARCHAR(64) NOT NULL,
 *     chromosome              VARCHAR(16),
 *     position                BIGINT,
 *     ref_allele              VARCHAR(32),
 *     alt_allele              VARCHAR(32),
 *     variant_type            VARCHAR(32),                      -- SNV/INDEL/CNV
 *     zygosity                VARCHAR(32),                      -- HOM/HET/COMPOUND_HET
 *     classification          VARCHAR(64),                      -- PATHOGENIC/LIKELY_PATHOGENIC/VUS/BENIGN
 *     hgvs_c                  VARCHAR(255),
 *     hgvs_p                  VARCHAR(255),
 *     evidence                TEXT,
 *     source_type             VARCHAR(32) NOT NULL DEFAULT 'PARSED',
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
 * );
 */
