package xenosoft.imldintelligence.module.clinical.internal.model;


@lombok.Data
public class ImagingReport {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long encounterId;
    private String modality;
    private String reportText;
    private Long fileId;
    private String sourceSystem;
    private java.time.OffsetDateTime examinedAt;
    private java.time.OffsetDateTime createdAt;
    
}

/**
 * Schema:
 * CREATE TABLE imaging_report (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                patient_id              BIGINT NOT NULL REFERENCES patient(id),
                                encounter_id            BIGINT REFERENCES encounter(id),
                                modality                VARCHAR(32),                      -- US/CT/MRI/PATHOLOGY
                                report_text             TEXT NOT NULL,                    -- 仅存结构化文字报告
                                file_id                 BIGINT REFERENCES file_asset(id), -- 报告附件（PDF等）
                                source_system           VARCHAR(32) NOT NULL DEFAULT 'PACS',
                                examined_at             TIMESTAMPTZ,
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */
