package xenosoft.imldintelligence.module.identity.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDate;
import java.time.OffsetDateTime;

@Data
@TableName("patient")
public class Patient {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private String patientNo;          // 系统内患者编号
    private String patientName;
    private String gender;
    private LocalDate birthDate;
    private String idNoEncrypted;     // 加密后的身份证号
    private String mobileEncrypted;   // 加密后的手机号
    private String patientType;       // INPATIENT/OUTPATIENT
    private String status;
    private String sourceChannel;     // HOSPITAL
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}

/**
 * Schema:
 * CREATE TABLE patient (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     patient_no              VARCHAR(64) NOT NULL,             -- 系统内患者编号
 *     patient_name            VARCHAR(100) NOT NULL,
 *     gender                  VARCHAR(16),
 *     birth_date              DATE,
 *     id_no_encrypted         VARCHAR(255),
 *     mobile_encrypted        VARCHAR(255),
 *     patient_type            VARCHAR(32) NOT NULL,             -- INPATIENT/OUTPATIENT
 *     status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 *     source_channel          VARCHAR(32) NOT NULL DEFAULT 'HOSPITAL', -- HOSPITAL
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     UNIQUE (tenant_id, patient_no)
 * );
 */