package xenosoft.imldintelligence.module.identity.internal.model;

import lombok.Data;

@Data
public class PatientExternalId {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private String idType;        // EMPI/MRN/ID_CARD/OTHER
    private String idValue;
    private String sourceOrg;     // 来源机构/系统
    private Boolean isPrimary;
    private java.time.OffsetDateTime createdAt;
}

/**
 * Schema:
 * CREATE TABLE patient_external_id (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     patient_id              BIGINT NOT NULL REFERENCES patient(id),
 *     id_type                 VARCHAR(32) NOT NULL,             -- EMPI/MRN/ID_CARD/OTHER
 *     id_value                VARCHAR(128) NOT NULL,
 *     source_org              VARCHAR(200),                     -- 来源机构/系统
 *     is_primary              BOOLEAN NOT NULL DEFAULT FALSE,
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     UNIQUE (tenant_id, id_type, id_value)
 * );
 */
