package xenosoft.imldintelligence.module.identity.internal.model;

import lombok.Data;

import java.time.OffsetDateTime;

@Data
public class Tenant {
    private Long id;
    private String tenantCode;
    private String tenantName;
    private String deployMode;   // PRIVATE_HOSPITAL / SAAS

    private String status;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

}
/**
 * Schema:
 * CREATE TABLE tenant (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_code             VARCHAR(64) NOT NULL UNIQUE,      -- 机构编码
 *     tenant_name             VARCHAR(200) NOT NULL,            -- 医院/机构名称
 *     # deploy_mode             VARCHAR(32) NOT NULL,             -- PRIVATE_HOSPITAL / SAAS
 *     status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
 * );
 */