package xenosoft.imldintelligence.module.screening.model;

@lombok.Data
public class QuestionaireResponse {
    private Long id;
    private Long tenantId;
    private Long questionnaireId;
    private Long tocUserId;
    private String responseNo;
    private java.math.BigDecimal riskScore;
    private String riskLevel;
    private String suggestion;
    private Boolean canShowPatient;
    private Boolean dataConsent;
    private java.time.OffsetDateTime createdAt;
    private java.time.OffsetDateTime expiresAt;
}

/**
 * CREATE TABLE questionnaire_response (
                                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                        questionnaire_id        BIGINT NOT NULL REFERENCES questionnaire(id),
                                        toc_user_id             BIGINT NOT NULL REFERENCES toc_user(id),
                                        response_no             VARCHAR(64) NOT NULL,
                                        risk_score              NUMERIC(10,4),
                                        risk_level              VARCHAR(32),
                                        suggestion              TEXT,
                                        can_show_patient        BOOLEAN NOT NULL DEFAULT TRUE,
                                        data_consent            BOOLEAN NOT NULL DEFAULT FALSE,   -- 是否授权流转院内
                                        created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                        expires_at              TIMESTAMPTZ,
                                        UNIQUE (tenant_id, response_no)
);
 */
