package xenosoft.imldintelligence.module.screening.model;


@lombok.Data
public class Questionaire {
    private Long id;
    private Long tenantId;
    private String questionnaireCode;
    private String title;
    private String description;
    private String diseaseScope;
    private String status;
    private Integer versionNo;
    private Boolean validatedFlag;
    private java.time.OffsetDateTime createdAt;  
}
/**
 * CREATE TABLE questionnaire (
                               id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                               questionnaire_code      VARCHAR(64) NOT NULL,
                               title                   VARCHAR(200) NOT NULL,
                               description             TEXT,
                               disease_scope           VARCHAR(64),
                               status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                               version_no              INT NOT NULL DEFAULT 1,
                               validated_flag          BOOLEAN NOT NULL DEFAULT TRUE,    -- 是否经权威验证
                               created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                               UNIQUE (tenant_id, questionnaire_code, version_no)
);
 */