package xenosoft.imldintelligence.modules.identity.internal.model;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.Data;

import java.time.OffsetDateTime;

@Data
public class AbacPolicy {
    private Long id;
    private Long tenantId;
    private String policyCode;
    private String policyName;
    private JsonNode subjectExpr;   // 主体条件（角色/科室/职称）
    private JsonNode resourceExpr;  // 资源条件（病种/院区/数据级别）
    private JsonNode actionExpr;    // 行为条件（READ/UPDATE/SIGN...
    private String effect;         // ALLOW / DENY
    private Integer priority;      // 优先级，数值越小优先级越
    private String status;
    private OffsetDateTime createdAt;
}

/**
 * Schema:
 * CREATE TABLE abac_policy (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     policy_code             VARCHAR(64) NOT NULL,
 *     policy_name             VARCHAR(100) NOT NULL,
 *     subject_expr            JSONB NOT NULL,                   -- 主体条件（角色/科室/职称）
 *     resource_expr           JSONB NOT NULL,                   -- 资源条件（病种/院区/数据级别）
 *     action_expr             JSONB NOT NULL,                   -- 行为条件（READ/UPDATE/SIGN...）
 *     effect                  VARCHAR(16) NOT NULL,             -- ALLOW / DENY
 *     priority                INT NOT NULL DEFAULT 100,
 *     status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     UNIQUE (tenant_id, policy_code)
 * );
 */
