package xenosoft.imldintelligence.modules.identity.internal.model;

import lombok.Data;

@Data
public class GuardianRelation {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private String guardianName;
    private String guardianMobileEncrypted;
    private String guardianIdNoEncrypted;
    private String relationType;  // FATHER/MOTHER/LEGAL_GUARDIAN/OTHER
    private Boolean isPrimary;
    private String status;
    private java.time.OffsetDateTime createdAt;
}

/**
 * Schema:
 * CREATE TABLE guardian_relation (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     patient_id              BIGINT NOT NULL REFERENCES patient(id),
 *     guardian_name           VARCHAR(100) NOT NULL,
 *     guardian_mobile_encrypted VARCHAR(255),
 *     guardian_id_no_encrypted VARCHAR(255),
 *     relation_type           VARCHAR(32) NOT NULL,             -- FATHER/MOTHER/LEGAL_GUARDIAN/OTHER
 *     is_primary              BOOLEAN NOT NULL DEFAULT FALSE,
 *     status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
 * );
 */