package xenosoft.imldintelligence.modules.identity.internal.model;

import lombok.Data;

import java.time.OffsetDateTime;

@Data
public class Role {
    private Long id;
    private Long tenantId;
    private String roleCode;
    private String roleName;
    private String description;
    private String status;
    private OffsetDateTime createdAt;
}

/**
 * Schema:
 * CREATE TABLE role (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     role_code               VARCHAR(64) NOT NULL,             -- SYSTEM_ADMIN/DOCTOR/CASE_MANAGER...
 *     role_name               VARCHAR(100) NOT NULL,
 *     description             TEXT,
 *     status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     UNIQUE (tenant_id, role_code)
 * );
 */
