package xenosoft.imldintelligence.modules.identity.internal.model;

import lombok.Data;

@Data
public class TocUser {
    private Long id;
    private Long tenantId;
    private String tocUid;           // ToC 体系唯一ID
    private String nickname;
    private String mobileEncrypted;  // 加密后的手机号
    private String openid;          // 小程序/公众号 OpenID
    private String unionid;         // 生态统一ID
    private String vipStatus;       // NORMAL/VIP
    private String status;
    private java.time.OffsetDateTime createdAt;
    private java.time.OffsetDateTime updatedAt;
}
/**
 * Schema:
 * CREATE TABLE toc_user (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     toc_uid                 VARCHAR(64) NOT NULL,             -- ToC 体系唯一ID
 *     nickname                VARCHAR(100),
 *     mobile_encrypted        VARCHAR(255),
 *     openid                  VARCHAR(128),                     -- 小程序/公众号 OpenID
 *     unionid                 VARCHAR(128),                     -- 生态统一ID
 *     vip_status              VARCHAR(32) NOT NULL DEFAULT 'NORMAL', -- NORMAL/VIP
 *     status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     UNIQUE (tenant_id, toc_uid)
 * );
 */