package xenosoft.imldintelligence.modules.identity.internal.model;

import lombok.Data;

@Data
public class UserRoleRel {
    private Long id;
    private Long tenantId;
    private Long userId;
    private Long roleId;
    private Long grantedBy;
    private java.time.OffsetDateTime grantedAt;
}

/**
 * Schema:
 * CREATE TABLE user_role_rel (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     user_id                 BIGINT NOT NULL REFERENCES user_account(id),
 *     role_id                 BIGINT NOT NULL REFERENCES role(id),
 *     granted_by              BIGINT REFERENCES user_account(id),
 *     granted_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     UNIQUE (user_id, role_id)
 * );
 */