package xenosoft.imldintelligence.modules.identity.internal.model;

import lombok.Data;

@Data
public class UserAccount {
    private Long id;
    private Long tenantId;
    private String userNo;
    private String username;
    private String passwordHash;
    private String displayName;
    private String userType;
    private String deptName;
    private String mobileEncrypted;
    private String email;
    private String status;
    private java.time.OffsetDateTime lastLoginAt;
    private java.time.OffsetDateTime createdAt;
    private java.time.OffsetDateTime updatedAt;
}

/**
 * Schema:
 * CREATE TABLE user_account (
 *     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
 *     user_no                 VARCHAR(64) NOT NULL,             -- 工号/账号编码
 *     username                VARCHAR(100) NOT NULL,
 *     password_hash           VARCHAR(255) NOT NULL,
 *     display_name            VARCHAR(100) NOT NULL,
 *     user_type               VARCHAR(32) NOT NULL,             -- DOCTOR/NURSE/ADMIN/FOLLOWER
 *     dept_name               VARCHAR(100),
 *     mobile_encrypted        VARCHAR(255),
 *     email                   VARCHAR(128),
 *     status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 *     last_login_at           TIMESTAMPTZ,
 *     created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     UNIQUE (tenant_id, user_no),
 *     UNIQUE (tenant_id, username)
 * );
 */