CREATE TABLE IF NOT EXISTS indicator_dict (
    code VARCHAR(64) PRIMARY KEY,
    indicator_name VARCHAR(200) NOT NULL,
    category VARCHAR(64) NOT NULL,
    data_type VARCHAR(16) NOT NULL,
    default_unit VARCHAR(32),
    loinc_code VARCHAR(64),
    normal_low NUMERIC(18, 6),
    normal_high NUMERIC(18, 6),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS indicator_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    source_system VARCHAR(32) NOT NULL,
    source_code VARCHAR(128) NOT NULL,
    source_name VARCHAR(200),
    target_indicator_code VARCHAR(64) NOT NULL REFERENCES indicator_dict(code),
    unit_conversion_expr VARCHAR(200),
    quality_rule JSONB,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, source_system, source_code)
);

CREATE TABLE IF NOT EXISTS lab_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    indicator_code VARCHAR(64) NOT NULL REFERENCES indicator_dict(code),
    value_numeric NUMERIC(18, 6),
    value_text VARCHAR(200),
    unit VARCHAR(32),
    reference_low NUMERIC(18, 6),
    reference_high NUMERIC(18, 6),
    abnormal_flag VARCHAR(16),
    source_type VARCHAR(32) NOT NULL,
    raw_data JSONB,
    collected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, encounter_id) REFERENCES encounter(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS clinical_history_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    history_type VARCHAR(32) NOT NULL,
    template_code VARCHAR(64),
    content_json JSONB NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    recorded_by BIGINT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, encounter_id) REFERENCES encounter(tenant_id, id),
    FOREIGN KEY (tenant_id, recorded_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS file_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    biz_type VARCHAR(32) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_ext VARCHAR(16),
    mime_type VARCHAR(100),
    file_size BIGINT,
    storage_provider VARCHAR(32) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    sha256 VARCHAR(64),
    uploaded_by BIGINT,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, uploaded_by) REFERENCES user_account(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS genetic_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    report_source VARCHAR(200),
    test_method VARCHAR(32),
    report_date DATE,
    file_id BIGINT,
    parse_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    summary TEXT,
    conclusion VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, encounter_id) REFERENCES encounter(tenant_id, id),
    FOREIGN KEY (tenant_id, file_id) REFERENCES file_asset(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS genetic_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    report_id BIGINT NOT NULL,
    gene VARCHAR(64) NOT NULL,
    chromosome VARCHAR(16),
    position BIGINT,
    ref_allele VARCHAR(32),
    alt_allele VARCHAR(32),
    variant_type VARCHAR(32),
    zygosity VARCHAR(32),
    classification VARCHAR(64),
    hgvs_c VARCHAR(255),
    hgvs_p VARCHAR(255),
    evidence TEXT,
    source_type VARCHAR(32) NOT NULL DEFAULT 'PARSED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, report_id) REFERENCES genetic_report(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS imaging_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    modality VARCHAR(32),
    report_text TEXT NOT NULL,
    file_id BIGINT,
    source_system VARCHAR(32) NOT NULL DEFAULT 'PACS',
    examined_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, patient_id) REFERENCES patient(tenant_id, id),
    FOREIGN KEY (tenant_id, encounter_id) REFERENCES encounter(tenant_id, id),
    FOREIGN KEY (tenant_id, file_id) REFERENCES file_asset(tenant_id, id)
);

CREATE INDEX IF NOT EXISTS idx_lab_result_tenant_patient_indicator_time
    ON lab_result (tenant_id, patient_id, indicator_code, collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_lab_result_tenant_encounter
    ON lab_result (tenant_id, encounter_id);

CREATE INDEX IF NOT EXISTS idx_genetic_report_tenant_patient_time
    ON genetic_report (tenant_id, patient_id, report_date DESC);

CREATE INDEX IF NOT EXISTS idx_genetic_variant_tenant_report_gene
    ON genetic_variant (tenant_id, report_id, gene);
