-- ============================================================
-- V8: Add sms_verification_code table (missing from old docker/init/01-identity.sql)
-- Applies to: databases initialized from stale docker-entrypoint-initdb.d scripts
-- Idempotent (IF NOT EXISTS) — safe to run on all deployments
-- ============================================================

CREATE TABLE IF NOT EXISTS sms_verification_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    purpose VARCHAR(32) NOT NULL,
    mobile_hash VARCHAR(64) NOT NULL,
    mobile_encrypted VARCHAR(255) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    verify_attempt_count INT NOT NULL DEFAULT 0,
    max_verify_attempts INT NOT NULL DEFAULT 5,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sms_verification_code_lookup
    ON sms_verification_code (tenant_id, purpose, mobile_hash, status, expires_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sms_verification_code_pending
    ON sms_verification_code (tenant_id, purpose, mobile_hash)
    WHERE status = 'PENDING';