-- Community module enhancement: post images, user notifications, board subscriptions

CREATE TABLE IF NOT EXISTS community_post_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    post_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, post_id) REFERENCES community_post(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS community_user_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    toc_user_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    related_post_id BIGINT,
    related_comment_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, toc_user_id) REFERENCES toc_user(tenant_id, id),
    FOREIGN KEY (tenant_id, related_post_id) REFERENCES community_post(tenant_id, id),
    FOREIGN KEY (tenant_id, related_comment_id) REFERENCES community_post_comment(tenant_id, id)
);

CREATE TABLE IF NOT EXISTS community_board_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    toc_user_id BIGINT NOT NULL,
    board_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, toc_user_id, board_id),
    FOREIGN KEY (tenant_id, toc_user_id) REFERENCES toc_user(tenant_id, id),
    FOREIGN KEY (tenant_id, board_id) REFERENCES community_board(tenant_id, id)
);

CREATE INDEX IF NOT EXISTS idx_community_post_image_tenant_post_sort
    ON community_post_image (tenant_id, post_id, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_community_notification_tenant_user_read_time
    ON community_user_notification (tenant_id, toc_user_id, is_read, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_community_subscription_tenant_user
    ON community_board_subscription (tenant_id, toc_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_community_subscription_tenant_board
    ON community_board_subscription (tenant_id, board_id, created_at DESC);
