package xenosoft.imldintelligence.module.report.model;

@lombok.Data
public class ReportTemplate {
    private Long id;
    private Long tenantId;
    private String templateCode;
    private String templateName;    
    private String diseaseCode;
    private String department;
    private com.fasterxml.jackson.databind.JsonNode templateSchema;
    private String status;
    private Integer versionNo;
    private Long createdBy;
    private java.time.OffsetDateTime createdAt;
    
    
}

/**
CREATE TABLE report_template (
                                 id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                 template_code           VARCHAR(64) NOT NULL,
                                 template_name           VARCHAR(100) NOT NULL,
                                 disease_code            VARCHAR(64),                      -- 可空：通用模板
                                 department              VARCHAR(100),                     -- 可空：通用模板
                                 template_schema         JSONB NOT NULL,                   -- 模板结构定义
                                 status                  VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
                                 version_no              INT NOT NULL DEFAULT 1,
                                 created_by              BIGINT REFERENCES user_account(id),
                                 created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 UNIQUE (tenant_id, template_code, version_no)
);
 */