package xenosoft.imldintelligence.module.report.model;


@lombok.Data
public class ReportVersion {
    private Long id;
    private Long tenantId;
    private Long reportId;
    private Integer versionNum;
    private com.fasterxml.jackson.databind.JsonNode contentSnapshot;
    private String changeSummary;
    private Long changedBy;
    private java.time.OffsetDateTime createdAt;
    
}
/**
 * Schema:
 * CREATE TABLE report_version (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                report_id               BIGINT NOT NULL REFERENCES report(id),
                                version_num             INT NOT NULL,
                                content_snapshot        JSONB NOT NULL,                   -- 全量快照
                                change_summary          TEXT,
                                changed_by              BIGINT REFERENCES user_account(id),
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                UNIQUE (report_id, version_num)
);
 */