package xenosoft.imldintelligence.module.report.model;

import com.fasterxml.jackson.databind.JsonNode;

@lombok.Data
public class Report {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long encounterId;
    private Long sessionId;
    private Long templateId;
    private String reportNo;
    private String status;
    private Integer currentVersion;
    private Long signedBy;
    private java.time.OffsetDateTime signedAt;
    private JsonNode signatureData;
    private Long createdBy;
    private java.time.OffsetDateTime createdAt;
    private java.time.OffsetDateTime updatedAt;
    
}

/**
 * Schema:
 * CREATE TABLE report (
                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                        patient_id              BIGINT NOT NULL REFERENCES patient(id),
                        encounter_id            BIGINT REFERENCES encounter(id),
                        session_id              BIGINT REFERENCES diagnosis_session(id),
                        template_id             BIGINT REFERENCES report_template(id),
                        report_no               VARCHAR(64) NOT NULL,
                        status                  VARCHAR(32) NOT NULL,             -- DRAFT/PENDING_REVIEW/APPROVED/SIGNED/ARCHIVED
                        current_version         INT NOT NULL DEFAULT 1,
                        signed_by               BIGINT REFERENCES user_account(id),
                        signed_at               TIMESTAMPTZ,
                        signature_data          JSONB,                            -- 兼容普通签名/CA签名元数据
                        created_by              BIGINT REFERENCES user_account(id),
                        created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                        updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                        UNIQUE (tenant_id, report_no)
);
 */
