package xenosoft.imldintelligence.module.screening.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "questionnaire_question", autoResultMap = true)
public class QuestionnaireQuestion {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long questionnaireId;
    private String questionNo;
    private String content;
    private String questionType;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode optionsJson;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private JsonNode scoringRuleJson;
    private Integer sortOrder;
    private Boolean requiredFlag;
    private java.time.OffsetDateTime createdAt;
}
/**
 * CREATE TABLE questionnaire_question (
                                        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                        questionnaire_id        BIGINT NOT NULL REFERENCES questionnaire(id),
                                        question_no             VARCHAR(32) NOT NULL,
                                        content                 TEXT NOT NULL,
                                        question_type           VARCHAR(32) NOT NULL,             -- SINGLE/MULTI/INPUT/SCALE
                                        options_json            JSONB,                            -- 选项定义
                                        scoring_rule_json       JSONB,                            -- 计分规则
                                        sort_order              INT NOT NULL,
                                        required_flag           BOOLEAN NOT NULL DEFAULT TRUE,
                                        created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                        UNIQUE (questionnaire_id, question_no)
);
 */
