package xenosoft.imldintelligence.module.screening.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@lombok.Data
@TableName("toc_clinical_transfer")
public class TocClinicalTransfer {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private Long responseId;
    private Long patientId;
    private String transferStatus;
    private Long approvedBy;
    private java.time.OffsetDateTime approvedAt;
    private String transferNote;
    private java.time.OffsetDateTime createdAt;    
}
/**
 * CREATE TABLE toc_clinical_transfer (
                                       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                       response_id             BIGINT NOT NULL REFERENCES questionnaire_response(id),
                                       patient_id              BIGINT REFERENCES patient(id),
                                       transfer_status         VARCHAR(32) NOT NULL,             -- PENDING/APPROVED/REJECTED/COMPLETED
                                       approved_by             BIGINT REFERENCES user_account(id),
                                       approved_at             TIMESTAMPTZ,
                                       transfer_note           TEXT,
                                       created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

 */