package xenosoft.imldintelligence.module.integration.internal.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import xenosoft.imldintelligence.common.mybatis.JsonNodeTypeHandler;

@lombok.Data
@TableName(value = "integration_job", autoResultMap = true)
public class IntegrationJob {
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    private Long tenantId;
    private String jobNo;
    private String sourceSystem;
    private String direction;
    private String bizType;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private com.fasterxml.jackson.databind.JsonNode requestPayload;
    @TableField(typeHandler = JsonNodeTypeHandler.class)
    private com.fasterxml.jackson.databind.JsonNode responsePayload;
    private String status;
    private String errorMessage;
    private java.time.OffsetDateTime startedAt;
    private java.time.OffsetDateTime finishedAt;
    private java.time.OffsetDateTime createdAt;

}
/**
 * CREATE TABLE integration_job (
                                 id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                 job_no                  VARCHAR(64) NOT NULL,
                                 source_system           VARCHAR(32) NOT NULL,             -- HIS/LIS/EMR/PACS
                                 direction               VARCHAR(16) NOT NULL,             -- INBOUND/OUTBOUND
                                 biz_type                VARCHAR(32) NOT NULL,             -- PATIENT/LAB/REPORT
                                 request_payload         JSONB,
                                 response_payload        JSONB,
                                 status                  VARCHAR(32) NOT NULL,             -- RUNNING/SUCCESS/FAILED/PARTIAL
                                 error_message           TEXT,
                                 started_at              TIMESTAMPTZ,
                                 finished_at             TIMESTAMPTZ,
                                 created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 UNIQUE (tenant_id, job_no)
);
 */
